### ISSUE TITLE
Python SWAT with SSL

### ISSUE THREAD

**Issue by Cazziii** [sassoftware/python-swat#10]
I have configured a server to use SSL for SAS Viya, however I am unable to connect using Python SWAT using either the SSL port 443 or the default CAS port 5570. Using 443 I get the message:

ERROR: The TCP/IP negClientSSL support routine failed with status 90bfc0e0.
ERROR: Failed to connect to host 'localhost', port 443.
Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.6/site-packages/swat/cas/connection.py", line 278, in __init__
    self._sw_connection = clib.SW_CASConnection(*params)
  File "/opt/anaconda/lib/python3.6/site-packages/swat/clib.py", line 86, in SW_CASConnection
    return _pyswat.SW_CASConnection(*args, **kwargs)
SystemError: <class 'py36swat.SW_CASConnection'> returned NULL without setting an error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda/lib/python3.6/site-packages/swat/cas/connection.py", line 285, in __init__
    raise SWATError(self._sw_error.getLastErrorMessage())
swat.exceptions.SWATError: Could not connect to 'localhost' on port 443.

Alternatively, using 5570 as the port I get the following:

ERROR: Kerberos initialization failed. Your credential cache is either expired or missing.
Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.6/site-packages/swat/cas/connection.py", line 278, in __init__
    self._sw_connection = clib.SW_CASConnection(*params)
  File "/opt/anaconda/lib/python3.6/site-packages/swat/clib.py", line 86, in SW_CASConnection
    return _pyswat.SW_CASConnection(*args, **kwargs)
SystemError: <class 'py36swat.SW_CASConnection'> returned NULL without setting an error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda/lib/python3.6/site-packages/swat/cas/connection.py", line 285, in __init__
    raise SWATError(self._sw_error.getLastErrorMessage())
swat.exceptions.SWATError: Could not connect to 'localhost' on port 5570.

**Comment by kesmit13** [comment]
The first thing I would do is make sure that your CAS server is configured to run on port 443.  That is the standard HTTPS port, but it might not be the one that your server is running on.  In the second case, are you using Kerberos authentication?  If not, it appears as though you are not specifying any authentication information, which is making it go through the Kerberos authentication attempt.

**Comment by kesmit13** [comment]
Also, I'm not sure what your connection parameters look like, but try adding protocol='https' to the parameters to make sure that it is connecting using HTTPS.

**Comment by kesmit13** [comment]
There were some changes to the way the protocol is detected in v1.2.1, so you might want to try installing that and seeing if that improves the situation.

**Comment by kesmit13** [comment]
I'm pretty sure this is simply an attempt to connect to an incorrect port.  I'm going to close it, but please correct me if I'm wrong.
