### ISSUE TITLE
astore.upload makes a wrong rest call

### ISSUE THREAD

**Issue by pinduzera** [sassoftware/python-swat#105]
Hello, I am trying to upload an astore through actionset but it just throws me an error:

``` python

s = swat.CAS("myserver.com", 
            8777, 
            "user", 
            "password")

s.loadactionset('aStore')

astore_name = "_C80O7P8PJUOIEXTSRM5VBDJC1_ast" ### already in server

s.table.loadTable(caslib = "Models",
                    path = astore_name + ".sashdat",
                    casout = {"name": astore_name, "caslib": "Models"}
                    )
      
store=s.download(rstore= {"name": astore_name, 
                          "caslib": "Models"})

with open('savelocal.sasast','wb') as file:
   file.write(store['blob']) ## I can download it
   

with open('savelocal.sasast','rb') as file:
      blob = file.read()
      
store_ = swat.blob(blob)

## where the Error occurs
s.astore.upload(store = store_,
               rstore= {"name": astore_name + "_version2", 
                             "caslib": "Models"},
                    )                          

```

At the last part, where i try to upload my file astore i get the following error:

``` python
SWATError: Invalid URL 'cas/sessions/0aac1cb0-196f-f749-8726-0c5ed6ae4e6f/actions/astore.upload': No schema supplied. Perhaps you meant http://cas/sessions/0aac1cb0-196f-f749-8726-0c5ed6ae4e6f/actions/astore.upload?
```

**Comment by kesmit13** [comment]
@pinduzera Could you post the full traceback?

**Comment by pinduzera** [comment]
> 
> 
> @pinduzera Could you post the full traceback?

Nevermind.
When I went to a refreshed session to show a proper traceback it just worked.
Probably had some connection instability.

What I face now what may suit another ticket is, that uploaded astore is not working well.

whe I stry `astore.score` I get the following errors:

```
ERROR: Unknown encoding.
ERROR: Critical TK KERNEL error
ERROR: Unknown encoding.
ERROR: Critical TK KERNEL error
ERROR: Action score failed.
ERROR: The action stopped due to errors.
```

**Comment by kesmit13** [comment]
I pushed some changes to fix some of the issues you are seeing. The handling of binary parameters and results wasn't complete. You should now be able to send a raw data value as a store=, and the result should have a blob field with the correct value in it.

I was also able the score using an astore file that I uploaded using the binary interface, but I haven't had any luck with REST myself. I've contacted the server-side developers to look into it. Once I uploaded the file using the binary interface, I was successfully able to score using it.

Was your astore file created using the same CAS server that you are trying to upload from, or was it generated elsewhere?

**Comment by kesmit13** [comment]
I'm going to close this one since it appeared to be a flakey network issue. There is a similar issue opened in R SWAT about using uploaded astore files that we can continue any further discussions on.
