### ISSUE TITLE
castable.plot.scatter not behaving as pandas dataframe.plot.scatter for parameter c=

### ISSUE THREAD

**Issue by gygabyte017** [sassoftware/python-swat#109]
Hi, consider this code:

```
df = pd.DataFrame(data=[[1, 1, "C1"], [2, 2, "C2"]], columns=["X", "Y", "C"])
df.plot.scatter(x="X", y="Y", c="C")  # It works

cas.upload_frame(df, casout="DF")
cas.CASTable("DF").plot.scatter(x="X", y="Y", c="C")  # Error:
# ValueError: 'c' argument must be a color, a sequence of colors, or a sequence of numbers, not C
```

In pandas, I can use the column "C" to determine the color based on its values, as per documentation (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.plot.scatter.html):

```
c: str, int or array_like, optional
The color of each point. Possible values are:
- A column name or position whose values will be used to color the marker points according to a colormap.
- ...
```

In pandas it works as expected but in swat I'm getting an error:
`ValueError: 'c' argument must be a color, a sequence of colors, or a sequence of numbers, not C`

What may be wrong?
Thank you

**Comment by kesmit13** [comment]
I'm thinking there must be an API difference in the latest version of pandas that is causing this difference. Essentially, all that happens when you do a `tbl.plot.scatter()` call is a sample set is downloaded to a `DataFrame` then it is plotted. However, on that `DataFrame` the method being called is `df.plot(..., kind='scatter')` rather than `tbl.plot.scatter(...)`. This is to be compatible with older versions of pandas. It may be that the behavior has diverged now.

You could try the following to see what happens. This is what happens internally with the substitution of `plot.scatter` rather than `plot(kind='scatter')`.
```
cas.CASTable('DF')._fetch().plot.scatter(x='X', y='Y', c='C')
```

**Comment by gygabyte017** [comment]
Thank you for your answer, so:

This works as expected!
`cas.CASTable('DF')._fetch().plot.scatter(x='X', y='Y', c='C')`

But also this works (I didn't expect that):
`df.plot(x="X", y="Y", c="C", kind="scatter")  # It works`

While this doesn't work (as you said):
`cas.CASTable('DF').plot(x='X', y='Y', c='C', kind="scatter")`

**Comment by kesmit13** [comment]
I'll have to change the way this works in the CASTable API so it works with both older and newer versions of pandas.

**Comment by kesmit13** [comment]
Although, I'm surprised your second one worked too. I wonder why that works, but the CASTable version doesn't.

**Comment by gygabyte017** [comment]
I agree it is weird, these two statements should follow the same code, shouldn't they?
`cas.CASTable('DF')._fetch().plot.scatter(x='X', y='Y', c='C')`
`df.plot(x="X", y="Y", c="C", kind="scatter")`

If it may be useful, I am using pandas version `1.1.1`.
Let me know if there is any test I can help you with.

**Comment by kesmit13** [comment]
I would think they would follow the same path, but there must be some difference in there. `tbl._fetch()` probably returns a `SASDataFrame` rather than a plain `DataFrame` though. I wonder what happens if you cast it first?
```
pd.DataFrame(cas.CASTable('DF')._fetch()).plot.scatter(x='X', y='Y', c='C')
```

**Comment by gygabyte017** [comment]
Wait sorry, I got confused. Let's summarize:

This works: `cas.CASTable('DF')._fetch().plot.scatter(x='X', y='Y', c='C')`
This does not: `cas.CASTable('DF').plot.scatter(x='X', y='Y', c='C')`

So the first `plot` is already acting on a `SASDataFrame`, and it works so no need to test it on a `DataFrame`.

The second one should be resolved as: `cas.CASTable('DF').plot(x='X', y='Y', c='C', kind="scatter")` and in fact it doesn't work as well.

However, `df.plot(x='X', y='Y', c='C', kind="scatter")` works.

But `cas.CASTable('DF')._fetch().plot(x='X', y='Y', c='C', kind="scatter")` works.

Therefore, it seems that the following are the two statements which are not equivalent:
`cas.CASTable('DF').plot(x='X', y='Y', c='C', kind="scatter") #KO`
`cas.CASTable('DF')._fetch().plot(x='X', y='Y', c='C', kind="scatter") #OK`

**Comment by gygabyte017** [comment]
Ok I think I got it. The problem I believe is that the `CASTablePlotter` is only able to fetch `x` and `y`, and not `c` (or `s`), so it is not passing the `c` column to pandas but instead the `c` parameter ends in the `**kwargs` and remains as it is: a string.

Maybe it should modified like this:
```
class CASTablePlotter(object):
    def _get_fetchvars(self, x=None, y=None, c=None, s=None, by=None):
        '''
        Return a list of variables needed for the plot

        '''
        if x is None and y is None and c is None and s is None:
            return None

        x = x or []
        if isinstance(x, six.string_types):
            x = [x]

        y = y or []
        if isinstance(y, six.string_types):
            y = [y]
            
        c = c or []
        if isinstance(c, six.string_types):
            c = [c]
            
        s = s or []
        if isinstance(s, six.string_types):
            s = [s]

        if by is not None:
            if isinstance(by, six.string_types):
                by = [by]
        else:
            by = self._table.get_groupby_vars()

        return list(by) + list(x) + list(y) + list(c) + list(s)

    def _get_plot_params(self, x=None, y=None, c=None, s=None, by=None, **kwargs):
        '''
        Split parameters into fetch and plot parameter groups

        '''
        params, kwargs = self._get_sampling_params(**kwargs)
        params['grouped'] = True
        params['fetchvars'] = self._get_fetchvars(x=x, y=y, c=c, s=s, by=by)
        return params, kwargs

    def __call__(self, x=None, y=None, c=None, s=None, kind='line', **kwargs):
        params, kwargs = self._get_plot_params(x=x, y=y, c=c, s=s, **kwargs)
        return self._table._fetch(**params).plot(x=x, y=y, c=c, s=s, kind=kind, **kwargs)

    def scatter(self, x, y, s=None, c=None, **kwargs):
        params, kwargs = self._get_plot_params(x=x, y=y, c=c, s=s, **kwargs)
        return self._table._fetch(**params).plot(x, y, s=s, c=c,
                                                 kind='scatter', **kwargs)
```

With this patch, all the above issues disappear. What do you think? If you agree I may pull a request, but I'm unsure about whether doing this would harm something else (and also unsure about whether every pandas `plot.shortcut` method need a `c` and a `s` parameter).

**Comment by kesmit13** [comment]
That does make sense. I can add these. After looking through the other plots, it appears as though `C` should also be added. I can't think of a reason this would break anything, but I'll run it through the tests and see what happens. Thanks for tracking it down.

**Comment by kesmit13** [comment]
I don't think that you need the modifications to `__call__` or `scatter`. The `c/s/C` in `_get_plot_params` should pull those parameters out of `**kwargs` if they exist.

**Comment by gygabyte017** [comment]
Tried, that is true for `__call__` but not for `scatter` because unfortunately it has those parameters in the signature:

`def __call__(self, x=None, y=None, kind='line', **kwargs):`
`def scatter(self, x, y, s=None, c=None, **kwargs):`

**Comment by kesmit13** [comment]
d45a4beeb470b2879d177b7f8d132a7f1d90f168 should fix this.

**Comment by gygabyte017** [comment]
I confirm everything works. Thank you very much, I can close the issue now.
