### ISSUE TITLE
Using Jupyter notebook and Swat in windows 

### ISSUE THREAD

**Issue by turanbul** [sassoftware/python-swat#11]
Hello,

I have installed swat using anaconda in Windows and I am getting following error when trying to connect to CAS server. Can you help me with this?

portnumber=5570 
sess = swat.CAS('10.X.X.X', portnumber, 'python-user', 'password', caslib="casuser") 
print (sess) 

The error is as follows:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-064e1c2196f8> in <module>()
      1 portnumber=5570
----> 2 sess = swat.CAS('10.X.X.X', portnumber, 'python-user', 'password', caslib="casuser")
      3 print (sess)

...\Anaconda3\lib\site-packages\swat\cas\connection.py in __init__(self, hostname, port, username, password, session, locale, nworkers, name, authinfo, protocol, **kwargs)
    243                 self._sw_error = rest.REST_CASError(a2n(soptions))
    244             else:
--> 245                 self._sw_error = clib.SW_CASError(a2n(soptions))
    246         except SystemError:
    247             raise SWATError('Could not create CAS error handler object. '

...\Anaconda3\lib\site-packages\swat\clib.py in SW_CASError(*args, **kwargs)
    118     ''' Return a CASError (importing _pyswat as needed) '''
    119     if _pyswat is None:
--> 120         _import_pyswat()
    121     return _pyswat.SW_CASError(*args, **kwargs)
    122 

...\Anaconda3\lib\site-packages\swat\clib.py in _import_pyswat()
     63     if not glob.glob(os.path.join(os.path.dirname(__file__), 'lib',
     64                                   platform, libname + '.*')):
---> 65         raise ValueError('The extensions for the binary protocol have not been '
     66                          'installed.  You can either install them using the full '
     67                          'platform-dependent install file, or use the REST interface '

ValueError: The extensions for the binary protocol have not been installed.  You can either install them using the full platform-dependent install file, or use the REST interface as an alternative.

I have the impression that this happens because I am running Jupyter from windows. Is that true? Or can you help me with this?

**Comment by kesmit13** [comment]
At the moment, you can only connect to the CAS REST port from Windows.  You are connecting to port (5570), which is the binary communications port.  You will need to determine what the REST port (http/https) that your server is using and use that instead.
