### ISSUE TITLE
adls2 caslib available?

### ISSUE THREAD

**Issue by ViaFerrata** [sassoftware/python-swat#110]
Hi there,

I'm just wondering if there is a possibility to upload files from an adls gen2 blob storage (e.g. ORC) to CAS?
Currently, I use the [addcaslib](https://documentation.sas.com/?cdcId=vdmmlcdc&cdcVersion=8.1&docsetId=caspg&docsetTarget=cas-table-addcaslib.htm&locale=en) method and a Teradata DB as a workaround (load table from blob storage, save data to TD, load from TD to CAS via swat). Seems like there is an S3 possiblity in the addcaslib, but not one for Azure blob storages?

The use case is to simply connect a blob storage table such that it can be used within SAS VA.

Thanks!

**Comment by saskir** [comment]
Hello ViaFerrata,
Please use the instructions found within the following link to contact SAS Tech Support.   We will be happy to assist you with this inquiry.

[Contact SAS Technical Support](https://support.sas.com/en/technical-support/contact-sas.html)

Thanks!
