### ISSUE TITLE
Wrong documentation example

### ISSUE THREAD

**Issue by pkaczynski** [sassoftware/python-swat#118]
There's a mistake in the documentation for [encryption errors](https://github.com/sassoftware/python-swat/blob/main/doc/source/encryption.rst).

The example states to set environment variable like this:
```
CAS_CLIENT_SSL_CA_LIST='/path/to/certificates.pem'
```
But if you do so, it doesn't work. The path should be without single quotes, like this:
```
CAS_CLIENT_SSL_CA_LIST=/path/to/certificates.pem
```

**Comment by kesmit13** [comment]
The specific syntax for setting environment variables varies depending on where you are doing it (shell, Python, etc.) possibly in addition to what shell you are using (bash, csh, Windows command shell). Quotes may be required in some instances depending on the path itself (for example, if it contains spaces). The example doesn't cover all cases, but gives a general indication of the environment variable syntax.
