### ISSUE TITLE
upload_frame change temporary csv location on Windows

### ISSUE THREAD

**Issue by gygabyte017** [sassoftware/python-swat#119]
Hi,
I noticed that when `upload_frame` is called, a temporary csv is created (dataframe -> csv -> upload) on Windows in the Temp folder on C: drive of the user executing the code.

Is that path customizable? I'm asking because usually in a multi partition file system on Windows, like the one I am using, the C: drive is very small sized and reserved to the OS, and a temporary file in there may fill out all the space causing issues with the OS.

Thank you

**Comment by kesmit13** [comment]
It just uses the standard Python `tempfile` package which I believe allows you to set an environment variable `TMPDIR` to point to a new root directory for temp files.

**Comment by gygabyte017** [comment]
I understand, you are referring to [https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir](url) right?

I'll try that out and let you know, thank you!

**Comment by gygabyte017** [comment]
Everything works as expected, thank you.
