### ISSUE TITLE
ERROR: Parameter 'showlabels' is not recognized.

### ISSUE THREAD

**Issue by ericlundy87** [sassoftware/python-swat#120]
I believe the same issue is happening in both R and python. Let me know if there is a better way to reference this other issue.

https://github.com/sassoftware/R-swat/issues/29

**Comment by kesmit13** [comment]
There is a fix for this in acfe3f4dba82275a140f56fd4ace37a65aa86dd5. It'll show up in the next release.

**Comment by kesmit13** [comment]
This is fixed in v1.9.3.
