### ISSUE TITLE
Binary Communication Advantages, R vs. Python

### ISSUE THREAD

**Issue by seanankenbruck** [sassoftware/python-swat#13]
I have a question regarding an advantage mentioned in the R documentation for SAS Viya 3.2 that I could not find in the Python documentation. In the [docs](http://documentation.sas.com/?docsetId=caspg3r&docsetTarget=p1e9nn48sdnb5sn10mikyke095y0.htm&docsetVersion=3.2&locale=en), one of the advantages to binary communication is "automatic encryption of communication if CAS is configured to perform TLS". 

Can you confirm that the same is true for Python? If a connection is made using the binary protocol is communication automatically encrypted if CAS is configured to perform TLS?

**Comment by kesmit13** [comment]
Both clients can be configured to communicate using encryption.  You need to set an environment variable CAS_CLIENT_SSL_CA_LIST to point to the certificates for that server.  With the v1.3.0 release of Python SWAT, you can also connect to the CAS REST server using encryption using the same environment variable.  The R client with that same feature will be out very soon.
