### ISSUE TITLE
Mypy stubs for swat

### ISSUE THREAD

**Issue by gygabyte017** [sassoftware/python-swat#136]
Hi, is there support for stubs? Mypy is always complaining about not finding swat stubs, but I can't find them anywhere (neither in a external package)

```
Mypy: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Mypy: Skipping analyzing "swat": module is installed, but missing library stubs or py.typed marker
```

Thank you

**Comment by bkemper24** [comment]
There is no support for mypy stubs.

According to the mypy doc, you may be able to suppress the warnings by adding a "# type: ignore" comment on the import line, like:
import swat  # type: ignore
