### ISSUE TITLE
Future Warning

### ISSUE THREAD

**Issue by Hossein-Tohidi** [sassoftware/python-swat#142]
I am recently getting these warning messages: 
C:\Users\username\Anaconda3\lib\site-packages\swat\cas\connection.py:1589: FutureWarning: the 'line_terminator'' keyword is deprecated, use 'lineterminator' instead.
  data.to_csv(filename, encoding='utf-8',
C:\Users\username\Anaconda3\lib\site-packages\swat\cas\connection.py:1424: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for key, value in df.dtypes.iteritems():

**Comment by bkemper24** [comment]
Thanks for pointing these out.  I will look into getting them fixed.
