### ISSUE TITLE
SWAT dependencies on OpenSSL libraries

### ISSUE THREAD

**Issue by githje** [sassoftware/python-swat#148]
Hi,

it seems that SWAT (tested with release 1.12, both Python and R-SWAT) requires older versions of `libcrypto.so` and `libssl.so` which might no longer be shipped with recent Linux distros (my environment is a Ubuntu 22.04 LTS). This is probably the same issue as discussed here: [https://github.com/sassoftware/python-swat/issues/106](https://github.com/sassoftware/python-swat/issues/106). Trying to initialize SWAT returns this error message in the notebook:

`RuntimeError: Booting the TK subsystem failed: TKECERT: Extension load failure.`

And:

`ERROR: Could not load opensslcert extension. OpenSSL libraries are not found or the wrong version.` 

(found in the container log of the  Jupyter notebook app). I was able to work around this issue by providing the required older library versions like this:

```
# extract *.so files from old openssl package
wget https://archlinux.org/packages/core/x86_64/openssl-1.1/download/ -O openssl-1.1-1.1.1.s-4-x86_64.pkg.tar.zst
tar --use-compress-program=unzstd -xvf openssl-1.1-1.1.1.s-4-x86_64.pkg.tar.zst
cp usr/lib/libcrypto.so.1.1 /usr/lib/x86_64-linux-gnu/
cp usr/lib/libssl.so.1.1 /usr/lib/x86_64-linux-gnu/

# set environment variables pointing to .so files in Jupyter config.
echo "os.environ[\"TKECERT_CRYPTO_LIB\"] = '/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1'" >> /etc/jupyter/jupyter_notebook_config.py
echo "os.environ[\"TKESSL_OPENSSL_LIB\"] = '/usr/lib/x86_64-linux-gnu/libssl.so.1.1'" >> /etc/jupyter/jupyter_notebook_config.py
```

**Comment by gygabyte017** [comment]
Hi, same happening to me now in k8s environment, which workaround do you suggest to fix without jupyter i.e. standard python executing a file `ENTRYPOINT python file.py`?
