### ISSUE TITLE
setuptools installation for sas viya

### ISSUE THREAD

**Issue by AmeerFaisalAdanan** [sassoftware/python-swat#16]
Hi. Im getting an error while installing python swat on a linux machine aside on my windows machine. i download the tar.gz file and install it using the command provided. an error said that "Could not import setuptools which is required to install from a source distribution.
Please install setuptools".  what setuptools i need to install to proceed with the installation of swat packages?

**Comment by fl0r3k** [comment]
Those are Pythons setuptools.Install for your distro.
https://packaging.python.org/guides/installing-using-linux-tools/

**Comment by kesmit13** [comment]
Just out of curiosity, what version of Python is this?  setuptools has been around for a very long time.  I'm wondering if your Python installation is too old to run SWAT.  You need to have at least Python 2.7.

**Comment by AmeerFaisalAdanan** [comment]
im using python 3.5. i do however update the pip packages to the latest version. since its my first time using swat library, i ran difficulty in searching help before proceeding to open issue thread here.

**Comment by kesmit13** [comment]
You should be able to just use pip to install setuptools.
```
pip install setuptools
```

**Comment by AmeerFaisalAdanan** [comment]
finished install. thank you for the help. just having problem connecting to company domain which i have ask the person in charge for the fix. Thank you
