### ISSUE TITLE
Import swat JSONDecodeError

### ISSUE THREAD

**Issue by j08rebelo** [sassoftware/python-swat#17]
Hi,

I'm trying to establish a connection from a jupyter notebook to a Viya Server.
I'm using the following connection details:

import swat 
portnumber=80
sess = swat.CAS('185.74.77.242', portnumber, 'python-user', 'xxxxxxxx', protocol='http')
print (sess)
csvtbl = sess.read_csv('https://raw.githubusercontent.com/sassoftware/sas-viya-programming/master/data/cars.csv')
csvtbl.head()

The output shows a few errors:
JSONDecodeError                           Traceback (most recent call last)
/home/jorge/anaconda3/lib/python3.5/site-packages/swat/cas/rest/connection.py in __init__(self, hostname, port, username, password, soptions, error)
    253                                              'cas/sessions'), data=b'')
--> 254                     out = json.loads(a2u(res.text, 'utf-8'))
    255                     if out.get('error', None):

/home/jorge/anaconda3/lib/python3.5/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    318             parse_constant is None and object_pairs_hook is None and not kw):
--> 319         return _default_decoder.decode(s)
    320     if cls is None:

/home/jorge/anaconda3/lib/python3.5/json/decoder.py in decode(self, s, _w)
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()

/home/jorge/anaconda3/lib/python3.5/json/decoder.py in raw_decode(self, s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

/home/jorge/anaconda3/lib/python3.5/site-packages/swat/cas/connection.py in __init__(self, hostname, port, username, password, session, locale, nworkers, name, authinfo, protocol, **kwargs)
    286                           a2n(soptions), self._sw_error)
    287                 if protocol in ['http', 'https']:
--> 288                     self._sw_connection = rest.REST_CASConnection(*params)
    289                 else:
    290                     self._sw_connection = clib.SW_CASConnection(*params)

/home/jorge/anaconda3/lib/python3.5/site-packages/swat/cas/rest/connection.py in __init__(self, hostname, port, username, password, soptions, error)
    273 
    274             except Exception as exc:
--> 275                 raise SWATError(str(exc))
    276 
    277     def _set_next_connection(self):

SWATError: Expecting value: line 1 column 1 (char 0)

Can anyone help me find what i may be doing wrong here?

SWAT version 1.3.0

**Comment by kesmit13** [comment]
I'm going to assume that there was an incorrect port number used here.  If you are still seeing the issue, let me know.

**Comment by SundareshSankaran** [comment]
@kesmit13, I face the same error 

Just to confirm : 
Is the port number the same port number on which you make a connection through SAS Studio ( i.e. - "cas;" in a SAS Studio program provides a log stating that the cas services are connected on port 5570 (in my case)) ?

I tried with both 5570, as well as 8777 (I saw you mention that this is the default REST port in another thread) - but both gave me the same error

**Comment by kesmit13** [comment]
@SundareshSankaran It's possible you are using encryption which uses port 443 by default.  If you are connecting through SAS Studio, you could always run the builtins.httpaddress action to see what port that returns.

**Comment by SundareshSankaran** [comment]
@kesmit13, thanks for your help. I understood the reason for this error was with regards to the trusted certificates (referred in another issue). 
We however tested that by logging into the actual server where Viya was located , and tried this out - therefore it worked with 5570 (the CAS port) rather than 443 which is the https port. Thanks again
