### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AmeerFaisalAdanan** [sassoftware/python-swat#18]
Maybe it is a dumb question. when we use the CAS.upload_file, it goes to the sas server. My question is, where can i search for caslib path in SAS environment manager? im new to sas swat and sas viya and i have little understanding in sas viya

**Comment by kesmit13** [comment]
I assume when you say "it goes to the sas server", you mean "it goes to the CAS server", correct?  I can't comment on any SAS interfaces since I only work with CAS specifically, but in SWAT you can see your caslibs using the conn.table.caslibinfo() method (which calls the 'table.caslibinfo' action).

**Comment by AmeerFaisalAdanan** [comment]
Yes, the cas server. One more question if you may. Since swat is similar to pandas, is it possible to use with other python libraries such as sklearn?

**Comment by kesmit13** [comment]
While we do have a CASTable object that supports much of the same API as a pandas DataFrame using CAS as the back-end, it won't work as an input data structure for packages such as sklearn.

**Comment by AmeerFaisalAdanan** [comment]
That sure helps a lot. so an alternative for the sklearn is to use actionset provided by the swat api right?

**Comment by kesmit13** [comment]
Correct.  There are CAS actionsets that provide similar functionality, as well as much more.  You may also want to check out the Pipefitter <https://github.com/sassoftware/python-pipefitter>  and DLPy <https://github.com/sassoftware/python-dlpy> packages.  There are higher-level Python packages built on top of SWAT.  Pipefitter has an API that is more like sklearn, and DLPy has a Keras-like API for deep learning applications.
