### ISSUE TITLE
No SWAT 1.14.0 for macOS Sequoia public beta

### ISSUE THREAD

**Issue by TomHsiung** [sassoftware/python-swat#184]
Hello, guys

Having some issues with the installation of SWAT on my macOS Sequoia Public Beta.

> username@Toms-iMac python % pip install swat==1.14.0
> ERROR: Could not find a version that satisfies the requirement swat==1.14.0 (from versions: 1.3.1, 1.4.0, 1.5.2, 1.6.1)
> ERROR: No matching distribution found for swat==1.14.0
> username@Toms-iMac python % python3 --version
> Python 3.12.4

The latest version of SWAT I could install on my machine is 1.6.1, which is not able to work with SAS Viya due to error:

> ValueError: The extensions for the binary protocol have not been installed.  You can either install them using the full platform-dependent install file, or use the REST interface as an alternative.

Thanks

**Comment by bkemper24** [comment]
Looks like you are running Python 3.12.4.  The swat package does not support Python 3.12 at this time, it only supports <= 3.11

**Comment by TomHsiung** [comment]
> The swat package does not support Python 3.12 at this time, it only supports <= 3.11
Great! Let met down grade my Python to 3.11 and thank you very much, pal.
