### ISSUE TITLE
Support for Polars

### ISSUE THREAD

**Issue by ahmedanadwc** [sassoftware/python-swat#189]
Hi,
Are there any plans to add support for [Polars](https://pola.rs/), as an alternative/addition to Pandas?
One way that could ease that support is using [Narwhals](https://narwhals-dev.github.io/narwhals/), at least that's what Altair used to provide [support to additional DataFrame libraries beside Pandas](https://pola.rs/posts/lightweight_plotting/) 

Thanks

**Comment by bkemper24** [comment]
There are no plans to add support for Polars at this time.
