### ISSUE TITLE
Swat : Error on connexion to CAS 

### ISSUE THREAD

**Issue by amonino** [sassoftware/python-swat#19]
Hello,
I try to connect to CAS server from python 2.7 and 3.5 (anaconda virtual envs) with swat.
Viya server is on a single linux machine and python is installed on it.
Version of swat used is 1.3.0.

My connexion code is:
import swat
s = swat.CAS('localhost', 5570, username='user', password='*******',protocol='cas')

I get the following Error:
ERROR: The TCP/IP negClientSSL support routine failed with status 807ff013.
ERROR: Failed to connect to host '192.168.0.28', port 5570.

SWATErrorTraceback (most recent call last)
<ipython-input-56-c1baa524843b> in <module>()
      1 import swat
----> 2 s = swat.CAS('localhost', 5570, username='user', password='******',protocol='cas')
      3 print(s)

/opt/anaconda3/envs/py27/lib/python2.7/site-packages/swat/cas/connection.pyc in __init__(self, hostname, port, username, password, session, locale, nworkers, name, authinfo, protocol, **kwargs)
    295 
    296         except SystemError:
--> 297             raise SWATError(self._sw_error.getLastErrorMessage())
    298 
    299         # Set up index origin for error messages

SWATError: Could not connect to '192.168.0.28' on port 5570.

I checked that cas is listening on port 5570 with netstat, and connected to the socket with telnet successfully.

Error messages are the same on python 2.7 and 3.5.

When connexion is made from python/swat, i can see messages like these in the cas log:
2018-05-09T03:47:49,939 INFO  [00000003] cas local MAIN NoUser  [tkcalsock.c:816] - New client connection accepted on port 5570. Client IP address and port are [::ffff:192.168.0.28]:57620.
2018-05-09T03:48:49,939 INFO  [00000003] cas local MAIN NoUser  [tkcalsock.c:816] - New client connection accepted on port 5570. Client IP address and port are [::ffff:192.168.0.28]:58710.
2018-05-09T03:49:49,939 INFO  [00000003] cas local MAIN NoUser  [tkcalsock.c:816] - New client connection accepted on port 5570. Client IP address and port are [::ffff:192.168.0.28]:59778.
2018-05-09T03:50:25,588 INFO  [00000003] cas local MAIN NoUser  [tkcalsock.c:816] - New client connection accepted on port 5570. Client IP address and port are [::ffff:192.168.0.28]:60472.

Thank you for your help.

**Comment by kesmit13** [comment]
The error message that contains 'TCP?IP negClientSSL' indicates that your server is configured with encryption.  You will need to set an environment variable pointing to the certificates used by your server.

See https://sassoftware.github.io/python-swat/encryption.html

**Comment by j08rebelo** [comment]
I have used export CAS_CLIENT_SSL_CA_LIST=/opt/sas/viya/home/SASSecurityCertificateFramework/cacerts/trustedcerts.pem
before starting the jupyter notebook and still i get this exact error.

What i'm i doing wrong?

**Comment by kesmit13** [comment]
Try using Python code to set it.  It may be that Jupyter isn't passing along the environment variables.

```
import os

os.environ['CAS_CLIENT_SSL_CA_LIST'] = '/opt/sas/viya/home/SASSecurityCertificateFramework/cacerts/trustedcerts.pem'
```

**Comment by kesmit13** [comment]
Just to verify, the trustedcerts.pem file is on your client side (the machine you are running Python on), correct?

**Comment by amonino** [comment]
Hello,
Tried with the certificate defined in the python session and It's now working.

Thanks a lot.

**Comment by j08rebelo** [comment]
This works:

import os

os.environ['CAS_CLIENT_SSL_CA_LIST'] =
'/opt/sas/viya/home/SASSecurityCertificateFramework/cacerts/trustedcerts.pem'

thank you!

2018-05-09 17:19 GMT+01:00 Kevin D Smith <notifications@github.com>:

**Comment by pwnaoj** [comment]
Hi,

I have the same issue. My Python version is 3.7 and SWAT version is 1.6.1.

This is the error i get

```
ERROR: The TCP/IP negClientSSL support routine failed with status 807ff008.
ERROR: Encryption run-time execution error
ERROR: Failed to connect to host 'my-ip-cas-server', port 5570.
```

This is my code

```
import swat

conn = swat.CAS('my-ip-cas-server', 5570, 'my-user', 'my-pass')
```

Thanks in advance.
