### ISSUE TITLE
Question about REST OS version 

### ISSUE THREAD

**Issue by roy12369** [sassoftware/python-swat#20]
Hi @kesmit13  ,
Since I saw the latest [SWAT version](https://github.com/sassoftware/python-swat/releases) and there is a REST API only tar.gz file for win64 platform. Does that mean I can use pyhon in windows platform to connect CAS library?
If so ,how should I config?
Many Thanks!
Roy

**Comment by fl0r3k** [comment]
1. Install SWAT for your OS using pip.
2. Get pem certificate file from your SAS Viya install and place it on your machine. It is located in **/opt/sas/viya/config/etc/SASSecurityCertificateFramework/cacerts/**
3. Run code:
```
import swat
import os
os.environ["CAS_CLIENT_SSL_CA_LIST"] = '/path/to/certificates.pem'
conn = swat.CAS(your-cas-controller, 8777, username, password, protocol='https')
conn.serverStatus()
```

**Comment by kesmit13** [comment]
Just to add a note to @fl0r3k's response, 8777 is the default REST port on the CAS server.  If you use a different port number, you'll have to change that as well.  

There is also a more terse way of connecting using a URL if you prefer:
```
conn = swat.CAS('https://your-cas-controller:8777', username, password)
```

**Comment by roy12369** [comment]
It works!
Many Thanks!
