### ISSUE TITLE
SWATError: Could not get session identifier. Error while communicating with server.

### ISSUE THREAD

**Issue by allej8** [sassoftware/python-swat#21]
Hello!

Based on some of the other issues reported in here I grabbed the trusted certificate file from our server using pscp and stuck it on my local machine. From there I executed the following:

```
import swat   
import os
os.environ["CAS_CLIENT_SSL_CA_LIST"] = 'C:/path/to/local/machine/certfile/trustedcerts.pem' 
conn = swat.CAS("https://server.name.com:8777", username = "username", password = "password")
```

However, I received a rather unhelpful error

```
SWATError: Could not get session identifier. Error while communicating with server. (ERROR: The session has no available workers.
ERROR: The action stopped due to errors.
)
```

Any ideas?

**Comment by kesmit13** [comment]
This sounds like a server-side problem.  Have you checked the server logs to see if there is anything out of the ordinary?

**Comment by allej8** [comment]
I did not check the server logs, however, I believe you are correct. The exact code worked just now for no apparent reason so it must have just been something funky with the server.
