### ISSUE TITLE
caslibify functionality needed in swat

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [sassoftware/python-swat#26]
for a given absolute path, there should be a function that analyzes the path and finds or creates a caslib. In the case of finding an existing caslib, the function should return the caslib along with the normalized path. In the case of creating one, it should also normalize the path and return to the user.

In addition to the functionality, the function should also consider the operating system of the client and server while performing its functionality. 

A simple version of this can be found in python-dlpy

This function is needed in multiple task therefore it should be centralized in swat.

**Comment by kesmit13** [comment]
I can see a function that checks for a caslib and if it exists, returns the caslib name, otherwise it creates one and returns that name.  However, the caslibify in python-dlpy seems to be very specific to DLPy.  I don't see that the task= parameter makes much sense for a general function.

**Comment by ethem-kinginthenorth** [comment]
the issue is that I added task is as follows:
if you want to load images from this path /a/b/c/d and if you create a caslib into /a/b/c/d, it does not work. It has to be something like: caslib: /a/b/c and path: d. 
I believe this kinda changes by action. so a flexible way (not necessarily with the task parameter) of handling this would be great.

**Comment by kesmit13** [comment]
A path_to_caslib method was added in e1458ea5c22d782e118e73b4ce6c1d4d51176678.  When passed a path, it will see if a caslib to that path (or a parent path) already exists.  If it does exist, it returns the name of that caslib and the relative path to the requested directory (blank if the requested directory is the same as the caslib directory).  If it does not exist, one is created.

The usage of parent folders seems to specific to be in a general function in SWAT.  If you want the parent folder, then you would need to set that folder as your path.
