### ISSUE TITLE
error check needed for len(table)

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [sassoftware/python-swat#27]
new_table = CASTable('new_table')
after this statement new_table lives in the client. 
when the statement below is called:
len(new_table) 
it returns an error.

Rather than this behavior, it should return something like "-1" to indicate that table is living in the client side.

**Comment by kesmit13** [comment]
I'm not sure I want to make a change like this.  I think if the table doesn't exist in the server, an error is appropriate.  If an actual number was returned, it might mask a real problem in code that comes later.

I'm still willing to listen to arguments though.

**Comment by ethem-kinginthenorth** [comment]
The issue is there is no way to check if a table lives in the client only. This on the other hand would help to make that difference.

**Comment by kesmit13** [comment]
There is the tableexists action for that purpose.
```
conn.tableexists(table=new_table)
```

The problem with len(...) is that it has to return a non-negative integer.  If it returns zero, it's not really true because the table doesn't exist.  It can't return a negative number is because it's very common in Python to do something like the following, and that would be broken.
```
if len(tbl):
    do.something()
```

**Comment by kesmit13** [comment]
I do agree that having an exists() method on the table might be nice since the tableexists action returns a CASResults object that you then have to check the 'exists' key in to get what you really want.
```
if conn.tableexists(table=new_table).exists:
    do.something()
```

While it would be a lot nicer to do:
```
if new_table.exists():
    do.something()
```

**Comment by ethem-kinginthenorth** [comment]
I am OK with exists() hopefully the latter choice.

**Comment by kesmit13** [comment]
exists() method added in f30529123838db733cd2eeab3ddb56c5afcff3c9
