### ISSUE TITLE
with swat.option_context(print_messages = False) nothing or all

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [sassoftware/python-swat#28]
this option "with swat.option_context(print_messages = False):" either hides everything or prints everything. This includes results tables as well. 

There should be an option where it should hide the messages but the result tables (that returns at the end of the completion of the action call) should be preserved.

e.g., below should print results tables not "None"
with swat.option_context(print_messages = False):
    r = action.call
    print(r)

**Comment by kesmit13** [comment]
Are you sure this isn't because you aren't calling the action?  r = action.call only returns a reference to the action.  r = action.call() call the action.

**Comment by ethem-kinginthenorth** [comment]
I am not sure what you mean. The function I need should disregard the notes/warnings/errors but should return the resulting result tables. 

If you have one already, and point me out an example. I am happy to check it out.

**Comment by kesmit13** [comment]
I'm going to need to see an actual test case.  From what I can tell, it works fine.

```
In [7]: with swat.option_context(print_messages=False):
   ...:     out = conn.summary(table='TMPRGNYOXGF')
   ...:     print(out)
   ...:
[Summary]

 Descriptive Statistics for TMPRGNYOXGF

         Column      Min       Max      N    ...          TValue          ProbT  Skewness   Kurtosis
 0         MSRP  10280.0  192465.0  428.0    ...       34.894059  4.160412e-127  2.798099  13.879206
 1      Invoice   9875.0  173560.0  428.0    ...       35.196963  2.684398e-128  2.834740  13.946164
 2   EngineSize      1.3       8.3  428.0    ...       59.656105  3.133745e-209  0.708152   0.541944
 3    Cylinders      3.0      12.0  426.0    ...       76.913766  1.515569e-251  0.592785   0.440378
 4   Horsepower     73.0     500.0  428.0    ...       62.173176  4.185344e-216  0.930331   1.552159
 5     MPG_City     10.0      60.0  428.0    ...       79.229235  1.866284e-257  2.782072  15.791147
 6  MPG_Highway     12.0      66.0  428.0    ...       96.729204  1.665621e-292  1.252395   6.045611
 7       Weight   1850.0    7190.0  428.0    ...       97.526890  5.812547e-294  0.891824   1.688789
 8    Wheelbase     89.0     144.0  428.0    ...      269.196577   0.000000e+00  0.962287   2.133649
 9       Length    143.0     238.0  428.0    ...      268.525733   0.000000e+00  0.181977   0.614725

 [10 rows x 17 columns]
```
