### ISSUE TITLE
Placement of constant in an operation - different behavior w.r.t. pandas and CAS table

### ISSUE THREAD

**Issue by SundareshSankaran** [sassoftware/python-swat#29]
As discussed with kesmit/SAS:

An operation on a pandas dataframe with a constant int added to a column (4+ df("C")) works, irrespective of 4+ df[c] or df[c]+4.

However, on a CAS column, the operation works only if the column is provided first.

Error & fine attached:
<img width="864" alt="errswat" src="https://user-images.githubusercontent.com/37813227/49025490-cd1ead80-f169-11e8-9709-9d1fa867e0d9.png">

**Comment by kesmit13** [comment]
Change pushed in 8ad75b69028ee68789af927aebfdff907810a925
