### ISSUE TITLE
swat version does not match

### ISSUE THREAD

**Issue by haghad** [sassoftware/python-swat#31]
![image](https://user-images.githubusercontent.com/44681869/49670783-c9294000-fa33-11e8-9e46-2095b86b2492.png)

The image above is showing my issue:
On the right, you see in my terminal that swat version 1.5.0 is installed in the environment,
yet when I start a jupyter notebook in that very same environment and query
`swat.__version__` it tells me I am using version 1.3.2-dev

Can someone please explain to me what is going on here?
I like to be certain about which version of a tool I'm using so that it is reproducible.
Thanks!

**Comment by kesmit13** [comment]
Odds are you are running Jupyter from one Python installation, and pip from a different one, and there are different versions of SWAT installed in them.  Make sure that 'which jupyter' and 'which pip' point to the same location.

**Comment by kesmit13** [comment]
In a background conversation, it was discovered this was due to a PYTHONPATH setting pointing to a different SWAT location.
