### ISSUE TITLE
access denied when connecting to CAS on a server that requires PEM file authentication

### ISSUE THREAD

**Issue by sascis** [sassoftware/python-swat#32]
I'm missing a step somewhere...  First of all, does the authentication required for SWAT relate at all to the authentication required for SASPY??  I'm in Jupyter Notebook, and I can start a SASPY session using the following SSH-type definition:

fall     = {'saspath' : '/opt/sas/spre/home/SASFoundation/bin/sas_u8',
            'encoding': 'latin1',
            'ssh'     : '/usr/bin/ssh',
            'host'    : 'special-user@machine.mycompany.com',
            'identity' : '/u/myuserid/identity_file.pem',
            'port'    : 22
            }
And I can connect to CAS from SASStudioV on that server, logging in as myself (not the special-user, above).  I have a .authinfo file setup with an entry to point to the server with my personal credentials.  But I'm very confused about how this all works - here's my error:

cas = swat.CAS('machine.mycompany.com', 5570, "myuserid", "myPassword")

ERROR: The TCP/IP negClientSSL support routine failed with status 803fd068.
ERROR: Failed to connect to host 'machine.mycompany.com', port 5570.

---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
~/miniconda3/envs/py36/lib/python3.6/site-packages/swat/cas/connection.py in __init__(self, hostname, port, username, password, session, locale, nworkers, name, authinfo, protocol, **kwargs)
    301                 else:
--> 302                     self._sw_connection = clib.SW_CASConnection(*params)
    303 

~/miniconda3/envs/py36/lib/python3.6/site-packages/swat/clib.py in SW_CASConnection(*args, **kwargs)
     93         _import_pyswat()
---> 94     return _pyswat.SW_CASConnection(*args, **kwargs)
     95 

SystemError: <class 'py36swat.SW_CASConnection'> returned NULL without setting an error

During handling of the above exception, another exception occurred:

SWATError                                 Traceback (most recent call last)
<ipython-input-13-8e7e9a2c8829> in <module>()
----> 1 cas = swat.CAS('machine.mycompany.com', 5570, "myuserid", "myPassword")  

~/miniconda3/envs/py36/lib/python3.6/site-packages/swat/cas/connection.py in __init__(self, hostname, port, username, password, session, locale, nworkers, name, authinfo, protocol, **kwargs)
    307 
    308         except SystemError:
--> 309             raise SWATError(self._sw_error.getLastErrorMessage())
    310 
    311         # Set up index origin for error messages

SWATError: Could not connect to 'machine.mycompany.com' on port 5570.

**Comment by kesmit13** [comment]
SASPy is a completely separate piece of software.  The only thing they share in authentication is that they both support .authinfo files.  However, I don't think that's your issue.  Your situation hasn't gotten to authentication yet.  Your situation looks like you are using encryption on the server, but you don't have your certificate configured on the client.  See https://sassoftware.github.io/python-swat/encryption.html#encryption.

**Comment by kesmit13** [comment]
There hasn't been any new updates on this issue in a while, so I'm going to close it.  It can be re-opened if there is still a need.
