### ISSUE TITLE
attribute error: module 'pandas.core.common' has no attribute 'in_qtconsole'

### ISSUE THREAD

**Issue by haghad** [sassoftware/python-swat#36]
![image](https://user-images.githubusercontent.com/44681869/52229749-af657700-2883-11e9-8a4c-2702b82b3043.png)

I don't think this is specific to calling this one command.

Using Pandas version 0.24.1

Can someone please explain to me what's going on and how to fix this issue?
Thank you very much.

**Comment by haghad** [comment]
Actually, I resolved my issue, by downgrading pandas:
conda install pandas=0.23.4

...but maybe something needs to be done for compatibility?

**Comment by kesmit13** [comment]
It looks like this function was removed recently.  I'll have to do something to work around it for newer versions of pandas.

**Comment by kesmit13** [comment]
This is fixed in 1972603b9e589e08bbe62a7c87abd1d326f1f2bc.
