### ISSUE TITLE
Writeback data on CAS

### ISSUE THREAD

**Issue by gygabyte017** [sassoftware/python-swat#38]
How to write a CASTable back to CAS?

Suppose I already have a table T on caslib PUBLIC. I create a CASTable which reefers to it:
`tb = conn.CASTable(caslib="PUBLIC", name="T")`

then for instance I filter it:
`tb2 = tb[tb['field']='filter']`

Now I want to writeback tb2 to CAS. How should I do it? I know I should drop the original T table, load tb2 on caslib and promote, but I don't understand how to do it with swat (especially the writing of the table).

Thanks!

**Comment by kesmit13** [comment]
The CASTable object doesn't have a method for this (yet), but you can call the `table.partition` action on the CASTable to "materialize" the table with all of the computed columns, filters, etc. applied.
```
tb.partition(casout="new-name")
```

**Comment by gygabyte017** [comment]
It works!

However, it also writeback in CAS the temporary columns used to filter:
`computedvars=['_ne_0_'], computedvarsprogram="_ne_0_"

Is this intended?

**Comment by kesmit13** [comment]
Yes, that's necessary because the computed columns can contain constructs that don't work in CAS table WHERE clauses.  However, for something as simple as a filter, you could use the CASTable.query(...) method.  That edits the WHERE clause directly and returns a new CASTable.
```
tb.query("field = 'filter'").partition(casout='new-name')
```

**Comment by gygabyte017** [comment]
I understand, thanks a lot!
