### ISSUE TITLE
SWATError: HTTP/1.1 403 Forbidden

### ISSUE THREAD

**Issue by sharminpathan** [sassoftware/python-swat#39]
conn = swat.CAS('xxxx',29032,protocol='http')

SWATError                                 Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\lib\site-packages\swat\cas\rest\connection.py in __init__(self, hostname, port, username, password, soptions, error)
    304                             raise SWATError('%s (%s)' % (out['error'], out['details']))
--> 305                         raise SWATError(out['error'])
    306 

SWATError: HTTP/1.1 403 Forbidden

During handling of the above exception, another exception occurred:

SWATError                                 Traceback (most recent call last)
<ipython-input-20-e6d186ca3f40> in <module>()
      1 import pandas as pd
      2 import swat
----> 3 conn = swat.CAS('xxxx',29032,protocol='http')

~\AppData\Local\Continuum\anaconda3\lib\site-packages\swat\cas\connection.py in __init__(self, hostname, port, username, password, session, locale, nworkers, name, authinfo, protocol, **kwargs)
    298                           a2n(soptions), self._sw_error)
    299                 if protocol in ['http', 'https']:
--> 300                     self._sw_connection = rest.REST_CASConnection(*params)
    301                 else:
    302                     self._sw_connection = clib.SW_CASConnection(*params)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\swat\cas\rest\connection.py in __init__(self, hostname, port, username, password, soptions, error)
    321 
    322             except Exception as exc:
--> 323                 raise SWATError(str(exc))
    324 
    325     def _set_next_connection(self):

SWATError: HTTP/1.1 403 Forbidden

**Comment by kesmit13** [comment]
How are you supplying your username and password?  403 typically means that the client can't authenticate.

**Comment by sharminpathan** [comment]
i have them stored in an authinfo file

**Comment by sharminpathan** [comment]
strange, i passed my local username password instead of the one on the server and it worked

**Comment by kesmit13** [comment]
You might want to try the latest release (1.5.1).  There was a change made to the hostname matching in authinfo files.  This may fix your issue.

**Comment by kesmit13** [comment]
There hasn't been any traffic on this issue in a while.  If the issue still remains, it can be re-opened.
