### ISSUE TITLE
swat.concat with queried CASTable

### ISSUE THREAD

**Issue by Mespith** [sassoftware/python-swat#42]
I am trying to concatenate two CASTables called _df_ and _newdata_. The code how I define the tables is added below. What I notice is that when I remove the query from _df_, the error does not appear. Does anyone know what the problem is here and how to fix it?
```
df = conn.CASTable("SIA_EXTRUSION_HISTORY", caslib="Public").query('datetime >= DHMS(today(),0,0,0)')
print(type(df))
df.head()
```
![image](https://user-images.githubusercontent.com/7500718/55939678-a8216780-5c3e-11e9-9589-02f6e882040c.png)

```
new_data = pd.DataFrame([new_values], columns=df.columns[:-1])
# Upload the new data to CAS and add the current datetime to the entry
new_data = conn.upload_frame(new_data, casout=dict(name="_temp_", caslib="casuser", replace=True))
conn.dataStep.runCode(code="""
        data casuser._temp_;
            set casuser._temp_;

            datetime = INTNX("hour", DHMS(today(),0,0,time()), 2, "same");
            format datetime DATETIME.;
        run;
    """
    )
print(type(new_data))
new_data.head()
```
![image](https://user-images.githubusercontent.com/7500718/55939830-0e0def00-5c3f-11e9-87d3-5767a24b8154.png)

```
# Append the new data to the old data
result = swat.concat([df, new_data])
```
![image](https://user-images.githubusercontent.com/7500718/55940017-85dc1980-5c3f-11e9-8b2f-eedc113cacb3.png)

**Comment by kesmit13** [comment]
I would try turning on action debugging to see what code is being generated, that might make things clearer.

	swat.options.trace_actions = True
	swat.options.trace_ui_actions = True

Kevin Smith
Kevin.Smith@sas.com

**Comment by kesmit13** [comment]
@Mespith Were you ever to get any more information on this, or get it working?

**Comment by Mespith** [comment]
I have not fixed it. I still use the query to create df and worked around the issue. It's fine by me if this issue is closed.
