### ISSUE TITLE
Import SWAT Appears to change TKESSL_OPENSSL_LIB variable

### ISSUE THREAD

**Issue by JinnyBoy94** [sassoftware/python-swat#44]
In my Jupyterhub environment, I have set up my c.Spawner.cmd to reference to the following set of codes:

```
 #!/bin/sh
 '''exec' /opt/anaconda3/bin/python "$0" "$@"
 ' '''
 # -*- coding: utf-8 -*-
 import re
 import sys
 import os
 
 from jupyterhub.singleuser import main
 
 if __name__ == '__main__':
     sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
     os.environ['CAS_CLIENT_SSL_CA_LIST']='/opt/sas/viya/config/etc/SASSecurityCertificateFramework/cacerts/trustedcerts.pem'
     os.environ['TKESSL_OPENSSL_LIB']='/usr/lib64/libssl.so.10'
     sys.exit(main())
```

Upon signing into jupyterhub, I decided to run the following set of codes:

```
import os
print(os.environ['TKESSL_OPENSSL_LIB'])
```

The following is the result of the execution: 
> /usr/lib64/libssl.so.10

Which is as expected.

However, when I ran the following set of codes:

```
import swat
print(os.environ['TKESSL_OPENSSL_LIB'])
```

The following is the result of the execution: 
> /opt/anaconda3/lib/libssl.so.1.1

Which is not as expected.

I'm on SWAT v1.5.1 with Anaconda v2019.03 built on Python 3.7. In case Viya shipping date is required, I'm on Viya shipping 19w25.

**Comment by kesmit13** [comment]
Yes, this is a problem.  This env setting was originally put in to make sure that the anaconda libssl was used, but now that it's been updated to 1.1, it doesn't work correctly anymore.  I pushed a change that should fix this (9223aa238673d4364b6c3f8732c9630ac5e8681f), but it will require using the GitHub version until a new release is done.

**Comment by kesmit13** [comment]
For now, if you set the env variable after importing SWAT, it should work.

**Comment by JinnyBoy94** [comment]
Hey Kevin, 

Thanks for replying. Noted on this. Will look forward to the fix :)
