### ISSUE TITLE
Build Python Rest service docker container with Python-SWAT

### ISSUE THREAD

**Issue by kchaksuvej** [sassoftware/python-swat#45]
I have successfully built SAS Viya Docker Container and I can access it using SAS Studio and Jupyter.

I try to create Python Rest Service docker with Python-SWAT to access CAS on SAS Viya Container above.

But I got error: 

Swat.exceptions.SWATError: Could not create CAS error handler object. Check your SAS TK path setting.

How to fix this error?

Did someone ever build "Python Rest Service docker with Python-SWAT"?

Thanks

**Comment by kesmit13** [comment]
This issue tracker is purely for the client itself, not for downstream packaging issues.  However, the error that you are seeing typically happens if you are using only the pure Python version of SWAT which does not contain the C extensions for binary communication with CAS servers.  Did you use the full SWAT installer, or just get the source from Github?

**Comment by kchaksuvej** [comment]
I'm not sure about C extensions for binary communication with CAS servers.
This is my dockerfile that I use to create image.

FROM python:3-onbuild
#ADD . /code
#WORKDIR /code
#COPY . /code
COPY . /usr/src/app
# Commands in a list
RUN pip install pandas
RUN pip install numpy
RUN pip install jsonify
RUN pip install python-swat-1.5.1-linux64.tar.gz
RUN yum -y install libXmu.x86_64RUN pip install -r requirements.txt
CMD ["python", "api.py"]

**Comment by kesmit13** [comment]
Do you have the full traceback?  I'm wondering if you have all of the other shared library dependencies.

**Comment by kchaksuvej** [comment]
What is full traceback?  Where can I find it? Thanks

**Comment by kesmit13** [comment]
Python should print a full traceback when it prints the error message and exits.

**Comment by kchaksuvej** [comment]
[swat.exceptions.SWATError_ Could not create CAS error handler object. Check your SAS TK path setting. __ Werkzeug Debugger.pdf](https://github.com/sassoftware/python-swat/files/3398467/swat.exceptions.SWATError_.Could.not.create.CAS.error.handler.object.Check.your.SAS.TK.path.setting.__.Werkzeug.Debugger.pdf)

**Comment by kesmit13** [comment]
Are there any other log messages?  It's not giving much information about what's going on.  It could be that your system needs libnuma installed, but that's more of a guess at this point.

**Comment by kchaksuvej** [comment]
How can I install libnuma in dockerfile? Thanks

**Comment by kesmit13** [comment]
That's a system level library that you'd have to install using whatever your distribution tools you use (presumably yum in this case).  Containerizing things is really beyond the scope of this project though.

**Comment by kesmit13** [comment]
Since this issue is more about creating containers than it is SWAT, I'm going to close it.
