### ISSUE TITLE
Observed Unusual Behavior with SWAT and Indices of Dataframe

### ISSUE THREAD

**Issue by vinayash** [sassoftware/python-swat#47]
I had two dataframes that were of the following format:

        C1  C2
    0   X    Y
    1   A    B

I wanted to append them together to create:

        C1  C2
    0   X    Y
    1   A    B
    0   X    Y
    1   A    B

I used the pd.concat() function.

I proceed to convert it into a dictionary, and then a CAS Table using to_dict() and CASTable.from_dict() respectively. 
After which, I convert into a sashdat file.

It's here that the problem arises. When I read the sashdat file back into a CAS Table, I notice that half of the observations vanish. Essentially equating to:

         C1  C2
     0   X    Y
     1   A    B

I tried resetting the index using reset.index() - since I thought that the repeating indices were somehow confusing SWAT in reading observations (maybe not the cause, but a guess).

This yielded:

        C1  C2
    0   X    Y
    1   A    B
    2   X    Y
    3   A    B

But after following the same process to create the sashdat file, the same problem existed. Only half of the table would appear.

After some troubleshooting, I rectified the error by creating a new column called 'ID' using;

df['ID'] = np.arange(len(df))
which yielded:

        C1  C2   ID
    0   X    Y    0
    1   A    B    1 
    2   X    Y    2   
    3   A    B    3

I reset the column 'ID' as the new index for the dataframe:

df.set_index('ID', inplace=True)

which gave the output:

     ID C1  C2
     0   X   Y
     1   A   B
     2   X   Y
     3   A   B

Converting into sashdat and loading it again to view the contents, I found that the issue has finally been rectified and  the whole table now shows up (all 4 observations).

Is this normal behavior? Was there a index limitation to sashdat files/SWAT where datasets cannot be read unless the index is in not duplicating and has a column name? 

This occurs whenever you append two or more dataframes together, as I tried it for a few other scenarios.

**Comment by kesmit13** [comment]
If you look at the output of to_dict(), you'll see that when pandas merges the dataframes, the values from the second dataframe override the existing values at the same indexes.  Each row needs to have a unique index value for this to work the way you want, or you need to use one of the other concat options to tell it how you want the merging to happen.

**Comment by vinayash** [comment]
Realized this issue is closed, and the issue has been solved. But wanted to ask as a simple thought of feedback:

Wouldn't it be useful to add an warning or some kind of message to the CASTAble.from_dict() or upload_frame() which warns the user of repeating index values or risk improper loading of data?

To novice users of python/SWAT, I would believe to be very handy information to have.

**Comment by kesmit13** [comment]
It's really more of a pandas issue than SWAT.  SWAT is merely passing the options along and letting pandas do the work, it doesn't do any sort of pre-processing or looking at the data to verify possible issues.
