### ISSUE TITLE
Connection Timed out 

### ISSUE THREAD

**Issue by veerendra-pappoppula** [sassoftware/python-swat#51]
I tried curl https://sasvad01.wcuds.net:5570 and it failed with the below error.

curl: (7) Failed to connect to sasvad01.wcuds.net port 5570: Timed out

I am trying to run to connect to CAS server from a terminal and not the server machine, so should I copy the certificate file from the server and copy it to any location?

I apologize for not being responsive in my previous post.

**Comment by kesmit13** [comment]
I don't think an incorrect certificate would cause this problem.  One thing I do wonder about is your protocol and port number.  5570 is the default port for the proprietary, binary protocol of CAS, whereas you have the protocol set to https.  I'm thinking the combination of those is what's causing a bad connection.  If you are sure that the port number is 5570, try a connection like the following:
```
conn = swat.CAS('sasvad01.wcuds.net', 5570)
```

**Comment by veerendra-pappoppula** [comment]
ERROR: The TCP/IP tcpSockConnect support routine failed with error 10060
(The connection has timed out.).
ERROR: Failed to connect to host 'sasvad01.wcuds.net', port 5570.
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\swat\cas\connection.py", line 303, in
__init__
    self._sw_connection = clib.SW_CASConnection(*params)
  File "C:\Python\lib\site-packages\swat\clib.py", line 94, in
SW_CASConnection
    return _pyswat.SW_CASConnection(*args, **kwargs)
SystemError: <class 'py37swat.SW_CASConnection'> returned NULL without
setting an error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    conn=swat.CAS('sasvad01.wcuds.net',5570)
  File "C:\Python\lib\site-packages\swat\cas\connection.py", line 310, in
__init__
    raise SWATError(self._sw_error.getLastErrorMessage())
swat.exceptions.SWATError: Could not connect to 'sasvad01.wcuds.net' on
port 5570.

**Comment by veerendra-pappoppula** [comment]
I tried it in python shell. and that is the error I received.

**Comment by kesmit13** [comment]
I've asked around and the only thing we can come up with is a firewall is stopping traffic on that port.  I don't know what sort of permissions you have on the server, but if you can run `sudo` you could check the firewall settings using the following:
```
sudo iptables --list-rules
```

**Comment by veerendra-pappoppula** [comment]
![image](https://user-images.githubusercontent.com/49684885/62474697-785c1980-b771-11e9-9695-a8833ff09eae.png)

**Comment by kesmit13** [comment]
Well, that's wide open.  I'm asking around a bit more to see if there is something you could run from your client machine to see if it can detect other connection issues for that port.

**Comment by kesmit13** [comment]
Can you try the following?  We still think there must be some sort of firewall issue.
```
A) activate telnet on the windows machine.
	dism /online /Enable-Feature /FeatureName:TelnetClient
B) test connectivity to the TKCAL port with
	telnet sasvad01.wcuds.net  5570
```
You won't be able to do anything using telnet, but it should at least let us know whether or not telnet can get through on that port.

**Comment by veerendra-pappoppula** [comment]
![image](https://user-images.githubusercontent.com/49684885/62486059-3ee4d780-b78c-11e9-9272-17832ad2d80d.png)

**Comment by veerendra-pappoppula** [comment]
The whole point of trying this is to read metadata information from the CAS server, on when some tables in a library got refreshed or modified, what are the url's of the reports/dashboards that are in a specific folder, and what datasets are they using. I was hoping to find this information after connecting to CAS, but if there is a better way to find this information programmatically, please let me know.

**Comment by kesmit13** [comment]
In order to get information about tables, you're going to have to connect and authenticate to a CAS server.  Otherwise, you won't have permissions to get any information from it.  As far as, "what are the url's of the reports/dashboards that are in a specific folder, and what datasets are they using", I'm not sure what you are referring to there since CAS doesn't have reports or dashboards, just actions.  

You could try connecting to CAS using the REST interface (which would be a different port than 5570, it would be the CAS server HTTP port) without SWAT, but I have a feeling you are going to run into connection problems there as well since SWAT connects using the Python requests package like you would likely use anyway.

https://developer.sas.com/apis/cas/rest/current/apidoc.html

**Comment by kesmit13** [comment]
BTW, my sources on the CAS team say that the fact that your telnet failed indicates that there is some sort of firewall between your Windows machine and the CAS server that is preventing connections on that port.

**Comment by veerendra-pappoppula** [comment]
Okay. Thank you very much for your help. I will keep digging. Please let me know if you want me to try something. I will check with my network team and see if they have any answers.

**Comment by kesmit13** [comment]
@veerendra-pappoppula Were you ever to get any more information on this, or get it working?

**Comment by veerendra-pappoppula** [comment]
I had to use a different module, Saspy, to do whatever I needed to do.

**Comment by veerendra-pappoppula** [comment]
I also had to use the server itself and not the terminal to perform the
task.

**Comment by kesmit13** [comment]
I'm going to assume this was due to a network issue.  It looks like you found another way to solve your issue, so I'm going to close this.  It can be re-opened if needed.
