### ISSUE TITLE
Issue with CASTable.merge

### ISSUE THREAD

**Issue by amagnani** [sassoftware/python-swat#54]
Hi there, 

I am getting this error while trying to merge two CASTables:
SWATError: No connection is currently registered

Here is my code:

df1 = pd.DataFrame({'key': ['foo', 'bar', 'baz', 'foo'],'value1': [1, 2, 3, 5]})
df2 = pd.DataFrame({'key': ['foo', 'bar', 'baz', 'foo'],'value2': [5, 6, 7, 8]})
table1=CASTable(df1)
table2=CASTable(df2)
merged_table=table1.merge(table2, how='inner', on='key')

Thanks in advance for any feedback you might have.

**Comment by kesmit13** [comment]
I've never seen that error before, but the code itself doesn't do what you might think it does.  The first parameter to a CASTable would be the name of the table, not a dataframe.  You have to create a CASTable then load the data.  I think this might be what you want.

```
table1 = conn.upload_frame(df1)
table2 = conn.upload_frame(df2)
```

**Comment by amagnani** [comment]
Thank you, this works perfectly!
