### ISSUE TITLE
upload_frame converts Boolean types to double and fills with NaNs

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [sassoftware/python-swat#57]
sess.upload_frame( df_test, casout=dict(name='test_table', replace=True))
test_table = sess.CASTable('test_table')
test_table.head(3) shows that Boolean types in the df is converted to double in CAS table and the content is filled with NaNs.

This is quite inconvenient while modeling

**Comment by pepriv** [comment]
I spoke to Ethem about this earlier, but here are some comments for others who might run into the same issue:

DataFrames are converted to CSV before they're uploaded to CAS. This removes all of the type information. You can explicitly set the data type of each column using the importoptions parameter or you can have CAS try to guess them. Either way, CAS will only accept the following types: char, varchar, double, int32 and int64. If it doesn't recognize the type, you will get a NaN. If you want to use a boolean, you should convert it to something that you can store in a CAS table (1/0, T/F, etc). For example, you could do something like this before uploading frames: 

`df.col1 = df.col1.astype(float)`

And then convert back to a boolean after reading those frames:

`df.col1 = df.col1.astype(bool)`
