### ISSUE TITLE
Anaconda2019.10 : .ix deprecated use loc or iloc instead

### ISSUE THREAD

**Issue by frasep** [sassoftware/python-swat#60]
After having installed Anadonda3 release 2019.10, latest one this day, many panda function with swat 1.5.2 didn't work because of deprecation of .ix method.

**Comment by kesmit13** [comment]
Can you be more specific?  It may be deprecated, but everything should still work.  However, you will get warnings until they get cleaned up.

**Comment by frasep** [comment]
I had errors when i used merge and sample methods for example. It works well if i go back to anaconda 5.2.0.

**Comment by kesmit13** [comment]
Fixed in b4c9db693b258f565ce5292ef797184e52148a76

**Comment by frasep** [comment]
Thanks Kevin.
