### ISSUE TITLE
SWATError: Unknown session

### ISSUE THREAD

**Issue by robdisseldorp** [sassoftware/python-swat#68]
Hi,

I am experiencing an unexplainable error when trying to connect via Python SWAT to a Viya 3.5 installation.

When calling the swat.CAS() action to create a connection I get a "swat.exceptions.SWATError: Unknown session" error. Further investigation seems to point in an error that is caused by the second call during the swat.CAS() execution:
POST /cas/sessions/{session}/actions/builtins.queryactionset HTTP/1.1 410 138

When simulating similar calls using plain REST API calls where I extracted the logic from connection.py resulted in more details on the error:

b'{\n  "status": 2720411,\n  "log": "ERROR: Parameter \'actionSet\' is required but was not specified.\\nERROR: The action stopped due to errors.\\n",\n  "logEntries": [\n    { "message": "ERROR: Parameter \'actionSet\' is required but was not specified.", "level": "error" },\n    { "message": "ERROR: The action stopped due to errors.", "level": "error" }\n  ],\n  "disposition": {\n    "severity": "Error",\n    "reason": "Abort",\n    "statusCode": 2720411,\n    "formattedStatus": "Error parsing action parameters.",\n    "debugInfo": "0x88bfc19b:TKCASA_GEN_PARSE_ERROR"\n  },\n  "changedResources": [  ],\n  "metrics": {\n    "elapsedTime": 0.000194,\n    "cpuUserTime": 0.098607,\n    "cpuSystemTime": 0.058004,\n    "systemTotalMemory": 33567145984,\n    "systemNodes": 3,\n    "systemCores": 4,\n    "memory": 0,\n    "osMemory": 9490432,\n    "systemMemory": 0,\n    "memoryQuota": 9490432,\n    "ioPageReclaims": 0,\n    "ioPageFaults": 0,\n    "ioReadFaults": 0,\n    "ioReadBlocks": 0,\n    "ioReadCalls": 0,\n    "ioWriteCalls": 0,\n    "ioReadBytes": 0,\n    "ioWriteBytes": 0,\n    "ioWriteBytesCancelled": 0,\n    "voluntaryContextSwitches": 0,\n    "involuntaryContextSwitches": 0,\n    "dataMovementBytes": 0\n  }\n}\n'

The code I used:

import base64
import os
import requests
import logging
import json

logging.basicConfig(level=os.environ.get("LOGLEVEL", "DEBUG"))

username = '<username>'
password = '<password>'
hostname = '<servername>'
port     = '8777'
cacert_file = '<path_to_trustedcerts.pem>

url = 'https://' + hostname + ':' + port + '/cas/sessions'

_auth = b'Basic ' + base64.b64encode(('%s:%s' % (username, password)).encode('utf-8')).strip()

_req_sess = requests.Session()

os.environ['CAS_CLIENT_SSL_CA_LIST'] = cacert_file

_req_sess.verify = os.environ['CAS_CLIENT_SSL_CA_LIST']
_req_sess.headers.update({
    'Content-Type': 'application/json',
    'Content-Length': '0',
    'Authorization': _auth,
})

# Create session
res = _req_sess.put(url, data=b'')

# Get information on nodes for this session
json = res.json()
sesId = json['session']
url = 'https://' + hostname + ':' + port + '/cas/sessions/' + sesId +'/actions/builtins.queryActionSet'

res = _req_sess.post(url, data=b'')

print(res.content)

The error: "ERROR: Parameter \'actionSet\' is required but was not specified" seems to indicate the 'builtins.queryActionSet' is missing

Any ideas?

May thanks,
Rob

**Comment by kesmit13** [comment]
I don't think your simulated code is doing the same thing as the swat.CAS code.  You are missing the extra parameters being sent on the HTTP request in your simulated code.  I'd be interested in seeing what the parameters are to your swat.CAS call though.  I think you may be missing something.  You could also turn the following on for more information:
```
swat.options.cas.debug.requests = True
swat.options.cas.debug.request_bodies = True
swat.options.cas.debug.responses = True
```

**Comment by robdisseldorp** [comment]
Thanks @kesmit13 for pointing that out. Applied this to normal swat.CAS() call and found the missing parameters. Applied these to REST only test script and now it works.

BTW: I am SAS colleague and acting on behalf of customer who is experiencing issue so trying to exclude swat by directly calling CAS REST API and simulating swat connection calls. "It works on my machine" and I can continue to diagnose specific customer issue.

**Comment by kesmit13** [comment]
What version of SWAT is this?  This error is familiar, but I thought we added some more logging information so that the error wasn't so vague.  You can use plain REST, but SWAT does do a lot of extra processing for you, and adds the CASTable object which makes working with CAS tables like working with pandas DataFrames.

**Comment by robdisseldorp** [comment]
They are using 1.6.0

Reason for using plain REST API is to rule out SWAT and check if direct works.

Everything works on my own environment. But at customer we get vague error. Trying to isolate issue.

Hopefully additional logging settings you provided will point to root cause. Plain REST eliminates extra layer

Sent from my iPhone

Op 8 feb. 2020 om 04:28 heeft Kevin D Smith <notifications@github.com> het volgende geschreven:

﻿

What version of SWAT is this? This error is familiar, but I thought we added some more logging information so that the error wasn't so vague. You can use plain REST, but SWAT does do a lot of extra processing for you, and adds the CASTable object which makes working with CAS tables like working with pandas DataFrames.

**Comment by pras135** [comment]
I am also getting the Unknown session from past few days.
It was working fine, but suddenly this error started comming.

```
import os
import swat
from dynaconf import settings 

swat.options.cas.debug.requests = True
swat.options.cas.debug.request_bodies = True
swat.options.cas.debug.responses = True
swat.options.cas.print_messages = True

username = settings.CAS_USERNAME
hostname = settings.CAS_HOST
port = settings.CAS_PORT
password = settings.CAS_PASSWORD

os.environ["CAS_CLIENT_SSL_CA_LIST"] = settings.CAS_CLIENT_SSL_CA_LIST 

conn = swat.CAS(hostname = hostname + ":{}".format(port), port = None, username = username, password = password) 
```

> PUT xxxx
> User-Agent: python-requests/2.22.0
> Accept-Encoding: gzip, deflate
> Accept: */*
> Connection: keep-alive
> Content-Type: application/json
> Content-Length: 0
> Authorization: b'Basic WjAwNDRYTks6R29vZHBsYWNlQDEzNQ=='
> 
> { "session": "510be4b7-629d-9045-b560-04e285e870f0" }
> 
> POST xxxx
> User-Agent: python-requests/2.22.0
> Accept-Encoding: gzip, deflate
> Accept: */*
> Connection: keep-alive
> Content-Type: application/json
> Content-Length: 73
> Authorization: b'Basic xxxx=='
> 
> {"actionset": "builtins.help", "_messagelevel": "error", "_apptag": "UI"}
> 
> {
>   "error": "Unknown session.",
>   "code": "SessionUnknown",
>   "details": "510be4b7-629d-9045-b560-04e285e870f0",
>   "disposition": null
> }
> 

> ---------------------------------------------------------------------------
> SWATError                                 Traceback (most recent call last)
> <ipython-input-9-50ec8ea13c73> in <module>
> ----> 1 conn = swat.CAS(hostname = hostname + ":{}".format(port), port = None, username = username, password = password)
> 
> C:\ProgramData\Anaconda3\lib\site-packages\swat\cas\connection.py in __init__(self, hostname, port, username, password, session, locale, nworkers, name, authinfo, protocol, **kwargs)
>     346                                            showhidden=True,
>     347                                            _messagelevel='error',
> --> 348                                            _apptag='UI').items():
>     349             self._actionset_classes[asname.lower()] = None
>     350             for actname in value['name']:
> 
> C:\ProgramData\Anaconda3\lib\site-packages\swat\cas\connection.py in retrieve(self, _name_, **kwargs)
>    1695         try:
>    1696             # Call the action and compile the results
> -> 1697             signature = self._invoke_with_signature(a2n(_name_), **kwargs)
>    1698             results = self._get_results(getnext(self, datamsghandler=datamsghandler),
>    1699                                         responsefunc=responsefunc, resultfunc=resultfunc)
> 
> C:\ProgramData\Anaconda3\lib\site-packages\swat\cas\connection.py in _invoke_with_signature(self, _name_, **kwargs)
>    1160         '''
>    1161         # Get the signature of the action
> -> 1162         signature = self._get_action_info(_name_)[-1]
>    1163 
>    1164         # Check for additional action parameters
> 
> C:\ProgramData\Anaconda3\lib\site-packages\swat\cas\connection.py in _get_action_info(self, name, showhidden)
>    1925             return self._action_info[name]
>    1926 
> -> 1927         asname, actname, asinfo = self._get_reflection_info(name, showhidden=showhidden)
>    1928 
>    1929         # If action name is None, it is the same as the action set name
> 
> C:\ProgramData\Anaconda3\lib\site-packages\swat\cas\connection.py in _get_reflection_info(self, name, atype, showhidden)
>    2014                                                            actionset=name,
>    2015                                                            _messagelevel='error',
> -> 2016                                                            _apptag='UI'):
>    2017                 for key, value in response:
>    2018                     if value:
> 
> C:\ProgramData\Anaconda3\lib\site-packages\swat\cas\connection.py in _invoke_without_signature(self, _name_, **kwargs)
>     945         '''
>     946         if isinstance(self._sw_connection, rest.REST_CASConnection):
> --> 947             errorcheck(self._sw_connection.invoke(a2n(_name_), kwargs),
>     948                        self._sw_connection)
>     949         else:
> 
> C:\ProgramData\Anaconda3\lib\site-packages\swat\cas\rest\connection.py in invoke(self, action_name, kwargs)
>     479             if self._results.get('disposition', None) is None:
>     480                 if self._results.get('error'):
> --> 481                     raise SWATError(self._results['error'])
>     482                 else:
>     483                     raise SWATError('Unknown error')
> 
> SWATError: Unknown session.

And while it was working fine, the output was:

> CAS(hostname, username, protocol='https', name='py-session-2', session='df87f0b3-8583-1846-ac5f-996e9ca11619')

I also tried reconnecting to already existing session, but that too fails with same error. Tried terminating the session and restart that also fails.

**Comment by kesmit13** [comment]
@pras135 I'm not sure what could have changed that would work one day then not work the next.  Do you have access to the server logs to see if anything useful is displayed there?

**Comment by kesmit13** [comment]
I'm assuming that since this was a while ago the issue was figured out.  I'm going to close the issue, but it can be re-opened if needed.
