### ISSUE TITLE
Python 3.8 compatible binary release for Windows

### ISSUE THREAD

**Issue by osuchw** [sassoftware/python-swat#71]
Pretty please?  Whenever you have a chance of course.
From what I see 1.6.1 has _py34swat.pyd all the way to _py37swat .pyd but no _py38swat.pyd
Thank you

**Comment by kesmit13** [comment]
Python 3.8 support should be out in May.  Things are currently being restructured with the SWAT releases which should alleviate these delays in the future.

**Comment by kesmit13** [comment]
SWAT v1.7.0 is now available with support for Python 3.8.
