### ISSUE TITLE
Not able to connect to CAS from Windows

### ISSUE THREAD

**Issue by venkattoluchuri** [sassoftware/python-swat#72]
I have been trying to run this from my local Jupyter notebook. However, I have copied trustedcerts.pem on to my local WIN machine. My viya is SSL enabled.
I copied the trustedcerts.pem file from the machine where my CAS server configured.
-----------------------------------------------
import swat
import os
os.environ['CAS_CLIENT_SSL_CA_LIST'] = 'C:/Users/vt7/Desktop/trustedcerts.pem'

import swat
conn = swat.CAS('myhost', '5570', 'vt7', 'XXXXX')

--------------------Below is the ERROR--------------------
ERROR: The TCP/IP negClientSSL support routine failed with status 807ff008.
ERROR: Encryption run-time execution error
ERROR: Failed to connect to host 'myhost', port 5570.

**Comment by kesmit13** [comment]
For Windows when you are connecting to CAS using the binary protocol (typically port 5570), you need to import the certificate into the Windows certificate store.  Instructions can be found here: https://go.documentation.sas.com/?docsetId=secref&docsetTarget=n12036intelplatform00install.htm&docsetVersion=9.4&locale=en . 

You may also need to import vault-ca.crt from your server as well.  Different server configurations use different certificates.  So try vault-ca.crt and trustedcerts.pem and see if that gets you connected.

**Comment by kesmit13** [comment]
On an additional note, the Windows client unfortunately has a split personality.  The binary protocol requires that you have the certificate in the Windows certificate store.  However, the CAS REST protocol uses the 'requests' Python package which doesn't support the certificate store; for that you have to use the environment variable.

**Comment by venkattoluchuri** [comment]
Will you be able to meet me on webex please?


Sent with BlackBerry Work (www.blackberry.com)
________________________________

**Comment by kesmit13** [comment]
Support can either be done through the Github issue tracker, or you can contact SAS Technical Support for other modes of support.  If you need something more than what can be done here, you can open a ticket at https://support.sas.com/en/technical-support/contact-sas.html.

**Comment by venkattoluchuri** [comment]
Thank you. My issue is resolved after I import on to my windows machine vault-deployTarget-ca.crt file
