### ISSUE TITLE
Handle CAS errors as Python Exception

### ISSUE THREAD

**Issue by gygabyte017** [sassoftware/python-swat#78]
I'm writing a large code which use tons of CAS actions. I'd like to write a robust code which deals with failed actions. However when an action fails, I see the "ERROR: ...." written in the console, however python has no idea that something was wrong and keeps executing the subsequent actions and generally the code.

What is a good way to handle errors? Should I check the CASResult for each instruction (seems verbose and boring....)? Or maybe there is a way to automatically raise i.e. a CASException when there is a corresponding "ERROR: ...."?

**Comment by kesmit13** [comment]
You can check the `CASResult.severity` attribute to see if a warning or error occurred.  A zero value means ok, 1 means a warning occurred, and 2 means an error occurred.  However, you can configure SWAT to raise exception instead by setting `swat.options.cas.exception_on_severity = 2`.  The default value is None.

**Comment by gygabyte017** [comment]
That's exactly what I needed, thank you very much.
For those interested, the exception raised will be `swat.exceptions.SWATCASActionError`.
