### ISSUE TITLE
Use SASFormatter to apply a SAS format to a SASDataFrame column

### ISSUE THREAD

**Issue by gygabyte017** [sassoftware/python-swat#80]
I have a local `SASDataFrame` with a column `Value` (as a result of a CAS action), and I would like to apply locally the `commax.` format to that Column.

I read about the `SASFormatter` object (which can also be passed as a constructor argument of `SASDataFrame`) however I couldn't figure out how to apply a format to a column.

Any hint?

Thank you

**Comment by kesmit13** [comment]
SASDataFrames have an attribute name `colinfo` which is a dictionary of `SASColumnSpec` objects.  Those objects have a `format` attribute that you can set.  In your case, it would look like this:
```
df.colinfo['Value'].format = 'commax'
```

**Comment by gygabyte017** [comment]
Thank you, so what is wrong with this code?

```
df = pd.DataFrame(data=[[10000],[20000],[30000]], columns=['Value'])
cas.upload_frame(df, casout=dict(name="TABLE", replace=True))
df = cas.CASTable("TABLE").fetch()["Fetch"]
df.colinfo["Value"].format = 'commax'
df
```

I would expect to see values like `10.000` but instead I still see unformatted values `10000.0`

**Comment by kesmit13** [comment]
I think you may have found a gap in the software.  Before SWAT was public, we did do SAS formatting of values when a format was available.  However, to be more compatible with pandas DataFrames, we disabled that, but never added an easy way to use it.

You could do something like this using pandas styler feature for now, although it only works with HTML.
```
df.style.format(dict(Value=lambda x: df.formatter.format(x, 'commax')))._repr_html_()
```

**Comment by kesmit13** [comment]
There is a new option in SWAT named `display.apply_formats`.  When set to `True`, all SASDataFrame rendering will apply the accompanying SAS formats.  Note that this does require you to be on a platform with the C extension (currently Linux and Windows only).
