### ISSUE TITLE
UI calls "simple.numrows" on dropped table when using CASTable.name

### ISSUE THREAD

**Issue by gygabyte017** [sassoftware/python-swat#81]
import swat
	import pandas as pd

	swat.options.cas.debug.requests = True
	swat.options.cas.debug.request_bodies = True
	swat.options.cas.debug.responses = True
	swat.options.cas.print_messages = True
	swat.options.cas.trace_actions = True
	swat.options.cas.trace_ui_actions = True

	cas = swat.CAS("site", 5570, 'user', '...')
	cas.sessionProp.setSessOpt(caslib="CASUSER", metrics=True)

	df1 = pd.DataFrame(data=[[1,2],[3,4]], columns=['A','B'])
	cas.upload_frame(df1, casout=dict(name="MYTABLE"))

	df2 = cas.CASTable("MYTABLE")

        # This works but then it continuously gives error
	cas.dropTable(name=df2.name, quiet=True)

Here's the relevant log (from uploading):

	NOTE: Executing action 'table.loadTable'.
	NOTE: Cloud Analytic Services made the uploaded file available as table MYTABLE in caslib CASUSER(user).
	NOTE: Action 'table.loadTable' used (Total process time):
	NOTE:       real time               0,074399 seconds
	NOTE:       cpu time                0,573008 seconds (770,18%)
	NOTE:       data movement time      0,003857 seconds
	NOTE:       total nodes             8 (768 cores)
	NOTE:       total memory            5,84T
	NOTE:       memory                  681,54M (0,01%)
	NOTE:       bytes moved             0,38K
	NOTE: The table MYTABLE has been created in caslib CASUSER(user) from binary data uploaded to Cloud Analytic Services.
	NOTE: Action 'table.upload' used (Total process time):
	NOTE:       real time               0,301992 seconds
	NOTE:       cpu time                0,608391 seconds (201,46%)
	NOTE:       total nodes             8 (768 cores)
	NOTE:       total memory            5,84T
	NOTE:       memory                  681,54M (0,01%)
	[builtins.queryactionset]
	   actionset     = "droptable" (string)
	   _messagelevel = "error" (string)
	   _apptag       = "UI" (string)
	[builtins.queryname]
	   name          = "droptable" (string)
	   _messagelevel = "error" (string)
	   _apptag       = "UI" (string)
	[builtins.reflect]
	   _messagelevel = "error" (string)
	   _apptag       = "UI" (string)
	   showhidden    = true (boolean)
	   actionset     = "table" (string)
	[table.droptable]
	   name  = "MYTABLE" (string)
	   quiet = true (boolean)
	NOTE: Executing action 'table.dropTable'.
	NOTE: Action 'table.dropTable' used (Total process time):
	NOTE:       real time               0,007185 seconds
	NOTE:       cpu time                0,021146 seconds (294,31%)
	NOTE:       total nodes             8 (768 cores)
	NOTE:       total memory            5,84T
	NOTE:       memory                  2,17M (0,00%)
	Out[2]: + Elapsed: 0.00718s, user: 0.00702s, sys: 0.0141s, mem: 2.17mb
	[builtins.queryactionset]
	   actionset     = "__len__" (string)
	   _messagelevel = "error" (string)
	   _apptag       = "UI" (string)
	[builtins.queryname]
	   name          = "__len__" (string)
	   _messagelevel = "error" (string)
	   _apptag       = "UI" (string)
	[builtins.queryname]
	   name          = "simple.numrows" (string)
	   _messagelevel = "error" (string)
	   _apptag       = "UI" (string)
	[builtins.reflect]
	   _messagelevel = "error" (string)
	   _apptag       = "UI" (string)
	   showhidden    = true (boolean)
	   actionset     = "simple" (string)
	[simple.numrows]
	   _apptag       = "UI" (string)
	   _messagelevel = "error" (string)
	   table.name = "MYTABLE" (string)
	NOTE: Executing action 'table.loadTable'.
	ERROR: The file or path 'MYTABLE' is not available in the file system.
	NOTE: Action 'table.loadTable' used (Total process time):
	NOTE:       real time               0,010474 seconds
	NOTE:       cpu time                0,035313 seconds (337,15%)
	NOTE:       total nodes             8 (768 cores)
	NOTE:       total memory            5,84T
	NOTE:       memory                  4,93M (0,00%)
	NOTE: Executing action 'simple.numRows'.
	NOTE: Action 'simple.numRows' used (Total process time):
	NOTE:       real time               0,000179 seconds
	NOTE:       cpu time                1,057902 seconds (591006,70%)
	NOTE:       total nodes             8 (96 cores)
	ERROR: Table 'MYTABLE' could not be loaded.
	ERROR: Failure opening table 'MYTABLE': A table could not be loaded.
	ERROR: The action stopped due to errors.
	NOTE:       total memory            747,58G
	NOTE:       memory                  0,00K (0,00%)
	[builtins.queryactionset]
	   actionset     = "__len__" (string)
	   _messagelevel = "error" (string)
	   _apptag       = "UI" (string)
	[builtins.queryname]
	   name          = "__len__" (string)
	   _messagelevel = "error" (string)
	   _apptag       = "UI" (string)
	[simple.numrows]
	   _apptag       = "UI" (string)
	   _messagelevel = "error" (string)
	   table.name = "MYTABLE" (string)
	NOTE: Executing action 'table.loadTable'.
	ERROR: The file or path 'MYTABLE' is not available in the file system.
	NOTE: Action 'table.loadTable' used (Total process time):
	NOTE:       real time               0,011604 seconds
	NOTE:       cpu time                0,040427 seconds (348,39%)
	NOTE:       total nodes             8 (768 cores)
	NOTE:       total memory            5,84T
	NOTE:       memory                  4,93M (0,00%)
	ERROR: Table 'MYTABLE' could not be loaded.
	ERROR: Failure opening table 'MYTABLE': A table could not be loaded.
	ERROR: The action stopped due to errors.
	NOTE: Executing action 'simple.numRows'.
	NOTE: Action 'simple.numRows' used (Total process time):
	NOTE:       real time               0,008666 seconds
	NOTE:       cpu time                1,107800 seconds (12783,29%)
	NOTE:       total nodes             8 (96 cores)
	NOTE:       total memory            747,58G
	NOTE:       memory                  0,00K (0,00%)

As you can see, after dropping (which is successful) the UI tries to call `table.loadTable` and `simple.numRows` on the dropped table, and of course it fails every time. And if I execute afterwards any python instructions, it again keeps printing all these errors.

I guess since I have the `df` variable which keeps a reference to a not-anymore-existing table, maybe there is some internal counter which tries to access the `df` referenced table?

What am I doing wrong?

Thank you!

**Comment by kesmit13** [comment]
Typically I would do it this way which is a bit cleaner.  I'll have to look into the issue.  The fact that it's showing '__len__' as the actionset name in some of those messages is very strange.
```
df2 = cas.upload_frame(df1, casout=dict(name="MYTABLE"))
df2.dropTable(quiet=True)
```

**Comment by kesmit13** [comment]
I'm not having any luck reproducing this.  What version of SWAT are you using?

**Comment by gygabyte017** [comment]
Latest, 1.6.1. May it be related to the IDE? I'm using PyCharm. Maybe it's Pycharm which queries the variables?

**Comment by gygabyte017** [comment]
(could you please delete your revision to my original post? It contained sensitive information by mistake, my latest revision is clean)

**Comment by kesmit13** [comment]
I think your suspicion about PyCharm may be correct.  It does do a lot more introspection than other IDEs and may be tripping code in SWAT.  I can't reproduce exactly what you are seeing, but I do get similar issues when working in a PyCharm console.  I'll have to see if there is a way to short circuit them.
