### ISSUE TITLE
Error connecting to CAS from Ubuntu

### ISSUE THREAD

**Issue by Mespith** [sassoftware/python-swat#84]
When connecting to CAS I got an error saying that the extensions for the binary were not installed. I'm using ubuntu as OS so I thought this should not be an issue. Any thoughts how I can make a binary connection?

**Operating system:**
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:          20.04
**Python version:** 3.8.2
**I installed swat using:**
python3 -m pip swat
**Error:**
Traceback (most recent call last):
  File "caffe_to_sas.py", line 9, in <module>
    sess = swat.CAS("viyawaves.sas.com", 5570, user='snljdk', password='')
  File "/usr/local/lib/python3.8/dist-packages/swat/cas/connection.py", line 267, in __init__
    self._sw_error = clib.SW_CASError(a2n(soptions))
  File "/usr/local/lib/python3.8/dist-packages/swat/clib.py", line 137, in SW_CASError
    _import_pyswat()
  File "/usr/local/lib/python3.8/dist-packages/swat/clib.py", line 67, in _import_pyswat
    raise ValueError('The extensions for the binary protocol have not been '
ValueError: The extensions for the binary protocol have not been installed.  You can either install them using the full platform-dependent install file, or use the REST interface as an alternative.

**Comment by kesmit13** [comment]
SWAT currently doesn't have binary support for Python 3.8.  You'll need to use Python 2.7 or 3.4-3.7, until the 3.8 extensions can be made available.

**Comment by Mespith** [comment]
Thank you for the explanation!

**Comment by kesmit13** [comment]
SWAT v1.7.0 is now available with support for Python 3.8.
