### ISSUE TITLE
Q: Possibility to monitor the CAS service 

### ISSUE THREAD

**Issue by rbfigueira** [sassoftware/python-swat#85]
Hi Team,

Sorry, this is not an issue, is more like a question ... if this Wrapper (SAS Scripting Wrapper for Analytics Transfer (SWAT)) has the power to monitor the CAS service to obtain the active sessions and "denied" (untreated) sessions (for example because an timeout).

I need to create an monitor type of system to get all info about the sessions calls on the CAS service.
Is that possible with the SWAT wrapper ?

Thanks

**Comment by kesmit13** [comment]
You can get a list of all of the active sessions by using the `listsessions` action.  However, any session creation errors would only show up in the log; they wouldn't be accessible by an action.

**Comment by rbfigueira** [comment]
Thanks for the information.

By the way, do you know, using the SWAT, if we can obtain the number of users online ? Is a basic feature that the Viya portal doesn't have. Thanks

**Comment by kesmit13** [comment]
Outside of using `listsessions`, there isn't any more information the client can return, so I'm going to close this one.
