### ISSUE TITLE
libnuma dependency failure doesn't show on jupyter 

### ISSUE THREAD

**Issue by datasciencemonkey** [sassoftware/python-swat#86]
I installed swat from pip when I built my docker image for jupyter. When using this container, on trying to use swat, the traceback was fairly esoteric.

/opt/conda/lib/python3.7/site-packages/swat/cas/connection.py in __init__(self, hostname, port, username, password, session, locale, nworkers, name, authinfo, protocol, **kwargs)
    267                 self._sw_error = clib.SW_CASError(a2n(soptions))
    268         except SystemError:
--> 269             raise SWATError('Could not create CAS error handler object. '
    270                             'Check your SAS TK path setting.')
    271 

SWATError: Could not create CAS error handler object. Check your SAS TK path setting.

I checked swat.options.tkpath that resolved to '/opt/conda/lib/python3.7/site-packages/swat/lib/linux'

So was wondering what the issue was, then later found this on the jupyter server log -

[W 15:40:55.775 NotebookApp] Notebook notebooks/Untitled.ipynb is not trusted
[I 15:40:56.046 NotebookApp] Kernel started: 55b9fe60-7f31-4b00-96fc-109d944c6ee4
** tkBoot failed:  Cannot dlopen [tkmk.so] : [libnuma.so.1: cannot open shared object file: No such file or directory]

tkBoot failed:  Cannot dlopen [tkmk.so] : [libnuma.so.1: cannot open shared object file: No such file or directory]

Could not get TK handle
tkBoot failed:  Cannot dlopen [tkmk.so] : [libnuma.so.1: cannot open shared object file: No such file or directory]

Could not get TK handle
tkBoot failed:  Cannot dlopen [tkmk.so] : [libnuma.so.1: cannot open shared object file: No such file or directory] **

Could not get TK handle

_This libnuma dependency resolution failure needs to be shown on the jupyter notebook itself, not on the logs.  This would really help as people run their containers most probably in detached mode._

**Comment by datasciencemonkey** [comment]
also, wanted to mention had IM'd Kevin - and re-installed swat using _conda install -c sas-institute swat_ . This time libnuma is also installed and everything worked ok. But the primary issue of the  log not showing in the notebook still needs to be resolved.

**Comment by kesmit13** [comment]
This has been fixed in the SWAT C extension internally.  It will be packaged with SWAT at the next CAS server release.

**Comment by datasciencemonkey** [comment]
Thanks Kevin!

**Comment by kesmit13** [comment]
Fixed in v1.8.0
