### ISSUE TITLE
negClientSSL error status 803fd068 when connecting.

### ISSUE THREAD

**Issue by CloudJanitor** [sassoftware/python-swat#87]
A bit of digging, this indicates a possible problem with libssl. 

Using Python 3.7.6, installed via pip & then tried conda, numactl is installed, not sure if relevant. I am a bit stumped on this one. 

Not sure where to start troubleshooting from here. This is on an ubuntu container, thoughts?

Actual error output below,

output from ldconfig -p | grep libssl.so
        libssl.so.1.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so.1.1
        libssl.so.1.0.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
        libssl.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so

"
ERROR: The TCP/IP negClientSSL support routine failed with status 803fd068.
ERROR: TK extension TKEAM could not be loaded. Most likely secure communications are not available on this system.
ERROR: Failed to connect to host 'ip-10-100-1-144.ec2.internal', port 5570.

---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/swat/cas/connection.py in __init__(self, hostname, port, username, password, session, locale, nworkers, name, authinfo, protocol, **kwargs)
    302                 else:
--> 303                     self._sw_connection = clib.SW_CASConnection(*params)
    304 

/opt/conda/lib/python3.7/site-packages/swat/clib.py in SW_CASConnection(*args, **kwargs)
    102         _import_pyswat()
--> 103     return _pyswat.SW_CASConnection(*args, **kwargs)
    104 

SystemError: <class 'py37swat.SW_CASConnection'> returned NULL without setting an error

During handling of the above exception, another exception occurred:

SWATError                                 Traceback (most recent call last)
<ipython-input-13-ae4ec9a29642> in <module>
----> 1 conn = swat.CAS('ip-10-100-1-144.ec2.internal',port=5570,password=os.environ.get('OAUTH2_TOKEN'))

/opt/conda/lib/python3.7/site-packages/swat/cas/connection.py in __init__(self, hostname, port, username, password, session, locale, nworkers, name, authinfo, protocol, **kwargs)
    308 
    309         except SystemError:
--> 310             raise SWATError(self._sw_error.getLastErrorMessage())
    311 
    312         # Set up index origin for error messages

SWATError: Could not connect to 'ip-10-100-1-144.ec2.internal' on port 5570.

"

**Comment by kesmit13** [comment]
The latest versions of SWAT require libssl 1.1.  Try setting the following environment variable
```
TKESSL_OPENSSL_LIB=/usr/lib/x86_64-linux-gnu/libssl.so.1.1
```

**Comment by CloudJanitor** [comment]
That did it, thanks boss.

Also found this article after much much much digging,

https://sassoftware.github.io/python-swat/encryption.html#unable-to-locate-libssl-on-the-client-side

**Comment by kesmit13** [comment]
Yep, that article is what I always reference when I see these issues.  I typically just search for the error code in Google and that page comes up. :)
