### ISSUE TITLE
Run into AttributeError with swat

### ISSUE THREAD

**Issue by zhaojohn** [sassoftware/python-swat#89]
I installed swat with pip on Redhat linux
$ sudo pip3 show swat
Name: swat
Version: 1.6.1

when I ran the code below, I got an error

import swat
conn = swat.CAS(hostname, portnum, usrid, passwd)

AttributeError: module 'swat' has no attribute 'CAS'

Thanks, 

John

**Comment by bosout** [comment]
Did you try setting your path to include the installed location of swat:

For example when swat is installed here:
/home/ubuntu/anaconda3

Try the following before starting python
export PYTHONPATH=/home/ubuntu/anaconda3:$PYTHONPATH

**Comment by zhaojohn** [comment]
Thanks, Bob.  I think we are making progress here.   The permission for swat was the issue of the previous error.  Now I ran into new problem.

$ python3 viya_test.py
ERROR: The TCP/IP negClientSSL support routine failed with status 807ff008.
ERROR: Encryption run-time execution error
ERROR: Failed to connect to host 'psdlax08.unx.sas.com', port 5570.
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/swat/cas/connection.py", line 303, in __init__
    self._sw_connection = clib.SW_CASConnection(*params)
  File "/usr/local/lib64/python3.6/site-packages/swat/clib.py", line 103, in SW_CASConnection
    return _pyswat.SW_CASConnection(*args, **kwargs)
SystemError: <class 'py36swat.SW_CASConnection'> returned NULL without setting an error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "viya_test.py", line 2, in <module>
    conn = swat.CAS(hostname, portnum, usrid, passwd)
  File "/usr/local/lib64/python3.6/site-packages/swat/cas/connection.py", line 310, in __init__
    raise SWATError(self._sw_error.getLastErrorMessage())
swat.exceptions.SWATError: Could not connect to 'psdlax08.unx.sas.com' on port 5570.

**Comment by kesmit13** [comment]
That error means that you don't have the correct certificate configured for your particular server.  The binary and REST protocols have different certificates by default.  For more information, see https://sassoftware.github.io/python-swat/encryption.html#incorrect-certificate-is-being-used.

**Comment by zhaojohn** [comment]
Thanks, Kevin.    I went through the doc in the link.   I defined the environment variables on my Redhat shell windows.  Still have the same error.   Note that the error code is 111.

ERROR: The TCP/IP tcpSockConnect support routine failed with error 111 (The connection was refused.).

**Comment by zhaojohn** [comment]
On the same machine,   I was able to connect to the same Viya instance via sas with the same .pem


1          cas casauto userid=jozhao host="psdlax08.unx.sas.com" port=5570;
NOTE: The session CASAUTO connected successfully to Cloud Analytic Services psdlax08.unx.sas.com using port 5570. The UUID is
      a158abc2-29ec-7c4e-ba35-72c780ef540b. The user is jozhao and the active caslib is CASUSERHDFS(jozhao).
NOTE: The SAS option SESSREF was updated with the value CASAUTO.
NOTE: The SAS macro _SESSREF_ was updated with the value CASAUTO.

In the same Linux session, I ran the python side and failed.

$ python3 viya_test.py
ERROR: The TCP/IP tcpSockConnect support routine failed with error 111 (The connection was refused.).
ERROR: Failed to connect to host 'psdlax08.unx.sas.com', port 5770.
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/swat/cas/connection.py", line 303, in __init__
    self._sw_connection = clib.SW_CASConnection(*params)
  File "/usr/local/lib64/python3.6/site-packages/swat/clib.py", line 103, in SW_CASConnection
    return _pyswat.SW_CASConnection(*args, **kwargs)
SystemError: <class 'py36swat.SW_CASConnection'> returned NULL without setting an error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "viya_test.py", line 4, in <module>
    conn = swat.CAS('psdlax08.unx.sas.com', 5770, authinfo='/home/jozhao/.authinfo')
  File "/usr/local/lib64/python3.6/site-packages/swat/cas/connection.py", line 310, in __init__
    raise SWATError(self._sw_error.getLastErrorMessage())
swat.exceptions.SWATError: Could not connect to 'psdlax08.unx.sas.com' on port 5770.

**Comment by kesmit13** [comment]
That one is a bit puzzling.  When I see a 111 error, I typically think that the server isn't allowing a connection to happen or there is a firewall issue.  But the connection from the SAS client makes that a bit more confusing.

**Comment by kesmit13** [comment]
@zhaojohn Did you ever figure this out?  I'm still puzzled by the 111 error since that means the client can't even reach the server.

**Comment by zhaojohn** [comment]
not, really.  I made it work doing.

 import os
 os.environ['CAS_CLIENT_SSL_CA_LIST'] = r"~/trustedcerts.pem"
 import swat
 conn=swat.CAS('https://{hostname}:443/cas-shared-default-http/',authinfo='~/.authinfo')

**Comment by kesmit13** [comment]
Since you have work-around, I'll close the issue.  You can re-open it if you still need help getting this working.
