### ISSUE TITLE
Error Handling HowTo

### ISSUE THREAD

**Issue by ViaFerrata** [sassoftware/python-swat#90]
Hi there,

I'm using swat to regularly upload tables from Teradata to a CAS server (using the fedsql action set).

Everything works great, however, I wonder what the intended way is to handle errors.
I.e., if a table is promoted to a global scope, where it already exists, an error is thrown on the CAS server, but it's not forwarded to python. And thus, the error can also not be forwarded, e.g. by triggering some alerts.

Now, I could probably print the output of every swat command and search for "error" strings, but as you can imagine this is quite ugly.

So is there an intended way to handle CAS errors in swat?

**Comment by gygabyte017** [comment]
Hi, see #78

**Comment by ViaFerrata** [comment]
Thank you, sorry for the duplicate!
