### ISSUE TITLE
Q: promote table and include sashdat file

### ISSUE THREAD

**Issue by ViaFerrata** [sassoftware/python-swat#91]
Hi there,

I'm using swat to load a table from a Teradata server to CAS via `fedSql`.
For this, the table is loaded and then promoted from a local to a global scope for a global caslib (see code below).
From Viya, I can see that the table then exists in the global caslib.

However, no associated `.sashdat` file exists.
Consequently, if the CAS server is restarted, the table is lost.

As far as I know, the `sashdat` table resides somewhere in the cache of the CAS server, I guess it's possible to promote it as well?
I just don't know how I can access it within swat.

Thank you!

```
c = swat.CAS(...)

# add Teradata caslib
c.table.addcaslib(lib='TDcaslib',
                  datasource={'srcType': 'teradata', 'dataTransferMode': 'serial', 'username': conf.username_td + '@LDAP',
                  'password': conf.password_td, 'server': conf.td_ip, 'database' : conf.database})
c.builtins.loadActionSet(actionSet='fedSql')

# load table from Teradata
c.fedSql.execDirect(query='CREATE TABLE {} AS (SELECT * FROM {});'.format(conf.table_out, conf.table))
  
# promote table to global scope, this creates the table in the global cas_target_lib, but no .sashdat file
c.table.promote(caslib='TDCaslib', drop=True, name=conf.table_out, target=conf.table_out, targetLib=conf.cas_target_lib)
```

**Comment by bosout** [comment]
If you want a .sashdat file, you need to submit a c.table.save action to write the .sashdat file to persistent storage.

An example is here:
https://go.documentation.sas.com/?docsetId=caspg&docsetTarget=p0l65oq3xsb06en1rnfzw3wj49tq.htm&docsetVersion=3.5&locale=en

**Comment by ViaFerrata** [comment]
Thank you! :)
