### ISSUE TITLE
Error using groupby

### ISSUE THREAD

**Issue by ljho6** [sassoftware/python-swat#92]
Hi,

I can connect to CAS and also I can load teh excel file but when I run the following code, I'm get an error 
TypeError: unhashable type: 'CASColumn' 

import saspy
import swat
import numpy as np
import pandas as pd

conn = swat.CAS("server", port, protocol='', username='', password='')

data = conn.read_excel('Input2-PendingList.xlsx', sheet_name='Pending List',dtype={"Zipcode": object, "Date": object})
data_ag = data['Date'].groupby([data['Date'], data['Zipcode']]).count().reset_index(name='Stops')

**Comment by kesmit13** [comment]
The `groupby` method takes a list of column names, not the columns themselves.
```
data['Date'].groupby(['Date', 'Zipcode'])
```

**Comment by kesmit13** [comment]
While using strings is the appropriate way to specify group names, I've added code that allows `CASColumn` references to also be passed in.  Note that the code only grabs the name of the column from the `CASColumn` it doesn't verify that the `CASColumn` actually belongs to the table being grouped.
