### ISSUE TITLE
upload_file API does not support the vars option

### ISSUE THREAD

**Issue by zhaojohn** [sassoftware/python-swat#94]
CAS loadTable Action supports parameter 'vars', but when I called  upload_file va SWAT.  I got an error below:

ERROR: Parameter 'vars' is not recognized.
ERROR: Expecting one of the following: importOptions, casOut, import, timeoutSec, timeoutSecs.
ERROR: The action stopped due to errors.
Traceback (most recent call last):
  File "run_nnet_scoring.py", line 42, in <module>
    casout={"caslib": 'Public',"name":'new_patients',"replace":True}
  File "/usr/local/lib64/python3.6/site-packages/swat/cas/connection.py", line 1468, in upload_file
    raise SWATError(out.status)
swat.exceptions.SWATError: Error parsing action parameters.

Here is my code:
import swat
conn = swat.CAS('https://psdlax08.unx.sas.com:443/cas-shared-default-http/',
              authinfo = '/home/jozhao/.authinfo')
url = "http://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data"
var_list = [
      {"name":"age","label":"age", "type" : "DOUBLE"},
      {"name":"sex","label":"sex", "type" : "DOUBLE" },
      {"name":"cp","label":"chestPainType", "type" : "DOUBLE"},
      {"name":"trestbps","label":"restingBloodPressure", "type" : "DOUBLE"},
      {"name":"chol","label":"serumCholestora", "type" : "DOUBLE"},
      {"name":"fbs","label":"fastingBloodSugar", "type" : "DOUBLE"},
      {"name":"restecg","label":"restingElectrocardiographic", "type" : "DOUBLE"},
      {"name":"thalach","label":"maxHeartRateAchieved", "type" : "DOUBLE"},
      {"name":"exang","label":"exerciseInducedAngina", "type" : "DOUBLE"},
      {"name":"oldpeak","label":"inDucedSTdepression", "type" : "DOUBLE"},
      {"name":"slope","label":"slopeOfPeakExerciseSTsegment", "type" : "DOUBLE"},
      {"name":"ca","label":"numOfMajorVesselsColoredByFlourosopy", "type" : "DOUBLE"},
      {"name":"thal","label":"", "type" : "DOUBLE"},
      {"name":"class_diag","label":"diagnosisOfHeartDisease", "type" : "DOUBLE"}
]

hdtbl = conn.upload_file(url,
                         importOptions={"fileType":"csv", "delimiter":","},
                         vars=var_list,
                         casout={"caslib": 'Public',"name":'new_patients',"replace":True}
                         )
conn.close()

**Comment by kesmit13** [comment]
`vars=` is not a top-level parameter.  It is a sub-parameter of `importOptions` in `loadtable` and `upload`.
