### ISSUE TITLE
tkBoot failed: The specified module could not be found tkmk.dll

### ISSUE THREAD

**Issue by gygabyte017** [sassoftware/python-swat#97]
I'm writing a large project, and sometimes I get this error:

`tkBoot failed: The specified module could not be found:  C:\project\env\sasexe\tkmk.dll`

I apologize since I'm not able to write a snippet to prove this error (the cas connection are created inside flask http calls, so I'm not sure which call generates this error and why).

However I was hoping that since you know the swat internals, maybe you could point me out why this may happen (maybe the environment gets corrupted?).

Thank you and sorry again for this generic question.

Edit: I'm using Windows with binary protocol and latest swat version 1.7.0

**Comment by kesmit13** [comment]
It does look like an environment issue.  It looks like the TKPATH environment variable is disappearing and SWAT can't find the TK DLLs anymore.  It should point to the swat/lib/win/ directory of your installed SWAT package.  From your error message, it looks like the variable isn't found and is going to a builtin default.  Off the top of my head, I'm not sure how it's happening though.

**Comment by gygabyte017** [comment]
Ok found it (luckily it was easier than I tought):

```
import swat
from flask import Flask

app = Flask(__name__)

if __name__ == '__main__':
    print("TKPATH= " + swat.options.tkpath)
    app.run(host="0.0.0.0", port="3200", debug=True)
```

output:
```
TKPATH= C:\myproject\myenv\lib\site-packages\swat\lib\win
 * Serving Flask app "flask_swat" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
TKPATH= ;
 * Debugger is active!
 * Debugger PIN: 133-144-631
 * Running on http://0.0.0.0:3200/ (Press CTRL+C to quit)
```

So it seems that when Flask restarts in debug mode the TKPATH is lost. If I set debug=False in Flask app.run, the server is not "* Restarting with stat" and TKPATH lives.
It seems totally related to Flask however, I keep investigating.

Thank you

**Comment by kesmit13** [comment]
I have to think this is in swat/clib.py:_initialize_tkpath.  There's not a lot going on in there other than looking up sys.platform to see what lib directory to use, then checking that directory to see if it contains the TK libraries.  I'm not sure what could be tripping that code up.

**Comment by kesmit13** [comment]
I found the problem here: https://github.com/sassoftware/python-swat/blob/6015573adc78efb853a1c0e721102a51d5ad0cc0/swat/clib.py#L174

After swat initializes the first time around, it sets the TKPATH variable to ';'.  This was a bug a while back where swat's initialization of TK was messing up other TK applications using a different set of TK libraries.  I'm not sure how to keep the fix for that and fix your issue too though.  A work-around would be to set a TKPATH env variable after importing swat.
```
import os
import swat
os.environ['TKPATH'] = swat.options.tkpath
```

**Comment by kesmit13** [comment]
As soon as I sent the last message, it occurred to me that I could just ignore TKPATH=';' in _initialize_tkpath.

**Comment by gygabyte017** [comment]
Hi, I'm reopening this issue since I'm experiencing a similar problem in a different situation.

This time I sometimes get `RuntimeError: Booting the TK subsystem failed: The specified module could not be found` directly during `import swat`:

```
Traceback (most recent call last):
  File "G:\app\myapp.py", line 3, in <module>
    import swat
  File "G:\app\env\lib\site-packages\swat\__init__.py", line 72, in <module>
    from . import config    # noqa: E402
  File "G:\app\env\lib\site-packages\swat\config.py", line 83, in <module>
    register_option('tkpath', 'string', set_tkpath, _initialize_tkpath(),
  File "G:\app\env\lib\site-packages\swat\utils\config.py", line 764, in register_option
    _config[key] = SWATOption(key, typedesc, validator, default, doc, environ=environ)
  File "G:\app\env\lib\site-packages\swat\utils\config.py", line 656, in __init__
    self._default = validator(default)
  File "G:\app\env\lib\site-packages\swat\config.py", line 54, in set_tkpath
    InitializeTK(a2n(path, 'utf-8'))
  File "G:\app\env\lib\site-packages\swat\clib.py", line 182, in InitializeTK
    out = _pyswat.InitializeTK(*args, **kwargs)
RuntimeError: Booting the TK subsystem failed: The specified module could not be found:  G:\app\env\sasexe\tkmk.dll
```

So here I can't even try to check `swat.options.tkpath` since the exception happens during import.

What could I do?

**Comment by kesmit13** [comment]
The TK DLLs should exist in G:\app\env\lib\site-packages\swat\lib\win\. Seeing the sasexe directory there makes me think that there's still an issue with the TKPATH environment variable setting. sasexe is part of the default path if it can't find one. You could try setting the following environment variable to see if this gets it working:
```
TKPATH=G:\app\env\lib\site-packages\swat\lib\win\
```

**Comment by gygabyte017** [comment]
> The TK DLLs should exist in G:\app\env\lib\site-packages\swat\lib\win
That is true, it does exists indeed.

Yes unfortunately (as I said maybe in some other posts) my application lives on a shared windows machine also with a SAS Foundation installation, so even though my application lives in an isolated conda env, I'm never sure about system environment variables which may conflict with my app.

However, manually setting
> TKPATH=G:\app\env\lib\site-packages\swat\lib\win\
either with shell before python entrypoint starts or with `os.environ` as first instruction it seems to be working again. (I hope!)

I don't know if there could be a rock solid method to stick to swat TKs' in every situation (from Flask, from multiprocessing spawn, from sys admin operations on windows, ...)

Anyway thank you as always!

**Comment by kesmit13** [comment]
The first thing I would check would be to see if there was a TKPATH environment variable in any of those situations. If so, that's always going to override. I'm not quite sure what is happening in this case since it wasn't finding the TK location at all and was just going to a built-in default. I'll have to try to reproduce it and see what's happening.

**Comment by jannichorst** [comment]
I Know this got closed a while back for anybody struggling with **virtual enviroments**, just write the following before importing swat:
`import os
os.environ["TKPATH"] = "venv\Lib\site-packages\swat\lib\win"`

while the path has to point at the win folder in your installed swat package. I don't know if this a general problem with virtual enviroments or your just my installation, but it resolved my import issues. 

FYI: 
1. "venv" is my virtual enviroment
2. make sure you give the right (relative) path when working in different subfolders
